content/sql/concepts/commands/delete.md
content/sql/concepts/commands/insert.md

New SQL glossary entry for INSERTs based on existing UPDATE and DELETE entries. Includes some errant typos I found while reading the DELETE entry.

Create SQL INSERT glossary entry; fix typos in DELETE entry

---

content/sql/concepts/commands/create-table.md
content/sql/concepts/index-in-sql.md

New text-heavy encyclopedia entry on SQL indexes including some basic best practices. While creating the syntax example for creating the index in the CREATE TABLE statement, I noticed that the CREATE TABLE entry itself had no syntax example, so I quickly added one.

Create SQL INDEX encyclopedia entry; Add syntax in CREATE TABLE entry

---

content/cpp/cpp.md
content/css/css.md
content/emojicode/emojicode.md
content/git/git.md
content/html/html.md
content/java/java.md
content/javascript/javascript.md
content/markdown/markdown.md
content/python/python.md
content/ruby/ruby.md
content/sql/sql.md
content/swift/swift.md

Changed the metadata field `Display Name` on topic files to `Title`, for consistency with topic and term files. They should now display correctly in the UI.
Looks like my text editor automatically added newlines to the end of each file I touched if there wasn't one already, so that would explain the rest of the diff.

Display Name -> Title

---

content/python/concepts/data-types/data-types.md

I don't see how the example showcases Python as strongly typed 😅... but regardless, the term is generally "strongly typed", not "strong type".

Fix "strong type" typo in python data-types

---

package.json

Per https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#choosing-the-right-license we default to not being licensed. Per @li-codecademy we're going to have a CLA bot running soon, but in the meantime this makes it a bit more explicit.

Added "license": "UNLICENSED" to package.json

---

content/html/concepts/semantic-html/terms/details/details.md
content/html/concepts/semantic-html/terms/summary/summary.md

This will pass the tests for linting. There were 2 trailing spaces in the recent commits which have caused the tests to go red.
I have verified that `npm run lint` and `npm run format:all` and `npm run format:verify` pass locally.
@sonnynomnom 
@lcart753

fix: remove trailing spaces to pass lint and formatter

---

documentation/content-standards.md

Small edit in `content-standards.md` documentation in Codebytes section.
* Rather than precede with three backticks, decided to surround language constants with them so as not to confuse contributors into thinking it is written as \```javascript (incorrect) as opposed to \```codebyte/javascript (correct).

style: removed extra backticks

---

content/general/concepts/angular/angular.md

Correcting grammar in the second to last paragraph.
This just corrects a typo I noticed when reading [Docs/General/Angular](https://www.codecademy.com/resources/docs/general/angular).

Correct typo in angular.md

---

content/general/concepts/yukihiro-matsumoto/yukihiro-matsumoto.md
content/python/concepts/built-in-functions/terms/abs/abs.md

In \docs\content\python\concepts\built-in-functions\terms\abs changes abs.md to include an example of the function working on a positive number so that those who may not know what an absolute value is don't think that the abs python function simply reverses the sign of the input.

Add example of abs on a positive number

---

content/react/concepts/react-native/terms/components/components.md

Update to the Components entry in the docs' React Native directory. This entry updates the URL addresses of the images included in the document and fixes those broken links.

Corrected images URLs for entry #1269

---

content/kotlin/concepts/data-types/data-types.md

Typo fix for free course slug under `CatalogContent`.

Update `ContentCatalog` in Kotlin: Data Types

---

content/cpp/concepts/math-functions/terms/cosh/cosh.md

Update `cosh.md` to fix a typo. In the LaTeX, the exponent `-x` needs to be in curly braces to remain fully in the exponent. Also added `\frac` to make the rendering prettier.
- [ x] Under "Development" on the right, I …

Correct latex in cosh term

---

content/python/concepts/built-in-functions/id/id.md
content/python/concepts/built-in-functions/terms/id/id.md

- Added the id() term for Python
- Closes issue #2146

[Term Entry] Python Built-in Function: .id()

---

content/javascript/concepts/arrays/terms/toSpliced/toSpliced.md

This PR fixes a typo in a comment regarding the elements of a list.
Linked to the merged PR #2910.

Fix typo in .toSpliced() method

---

content/swift/concepts/structures/structures.md

I noticed that on the [site](https://www.codecademy.com/resources/docs/swift/structures) **the link doesn't show up properly** because of the wrong braces. Here is the screenshot of it:
Fixed the braces in this request.

Swift Structures: Fixed the braces so that link shows correctly in ../swift/structures/structures.md file.

---

content/python/concepts/strings/terms/split/split.md

Closes #3402 
This edit is for the Python Strings: [Split](https://www.codecademy.com/resources/docs/python/strings/split) method located under the file path docs/content/python/concepts/strings/terms/split/split.md
Edit the syntax section to clarify that the second parameter in the split() method is the maximum number of splits. Also include the default when a number isn't given.
My changes:
- Edit syntax section to clarify that the second parameter in the split() method is the maximum number of splits
- Rename second parameter from `number_of_items` to `maxsplit` for clarification as to what this parameter does. It is not a count for the number of items, instead it sets a maximum number of times the string can be split.
- Explain what the default value is if second parameter is not …

Update syntax for second parameter in split() method

---

content/dart/concepts/type-conversion/terms/tryParse/tryParse.md

- Added the tryParse() term for Dart. 
- Mardown file entry is under: docs/tree/term-tryParse/content/dart/concepts/type-conversion 
- Closes #4572
- [ x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

[Term Entry] Dart Type Conversion .tryParse() #4572

---

content/kotlin/concepts/operators/operators.md

Under the "Logical Operators" heading, it shows the "OR" operator as two exclamation points "!!" &mdash; this is not correct. It should be two vertical lines "||"
reported through customer support via this ticket: https://codecademy.atlassian.net/browse/CQ-6994
N/A
- Editing an existing entry: Correction
- [ x ] All writings are my own.
- [ x ] My entry follows the Codecademy Docs style guide.
- [ x ] My changes generate no new warnings.
- [ x ] I have performed a self-review of my own writing and code.
- [ x ] I have checked my entry and corrected any misspellings.
- [ x ] I have made corresponding changes to the documentation if needed.
- [ x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x ] I have confirmed that I'm pushing from a new branch named …

correct "Or" operator from "!!" to "||"

---

content/dart/concepts/queue/terms/contains/contains.md
content/python/concepts/sets/terms/issubset/issubset.md

Added a term entry that describes the Python set method `issubset()`.
Closes #4613

[Term Entry] Python sets .issubset() #4613

---

content/dart/concepts/type-conversion/terms/toString/toString.md

- Added .toString() type conversion for Dart
- Closed Issue #4565 

[Term Entry] Dart Type Conversion .toString()

---

content/css/concepts/selectors/selectors.md

I have made update in selectors.md in CSS. i put a topic of group selector in it which was not there but it is important. When one or more selectors have same style. we can use group selector to minimize the code

I add how to use group selector in selectors.md

---

content/pandas/concepts/dataframe/terms/columns/columns.md
content/pandas/concepts/dataframe/terms/index/index.md

Added entries for the .index and .columns attributes of DataFrames. 
Closes #4518
Closes #4519

Create index and columns

---

content/postgresql/concepts/comments/comments.md

Create comments.md under postgresql

---

content/python/concepts/sets/terms/discard/discard.md

I have created the article about the `.discard()` method for set objects in Python.
It's my first contribution to  GitHub, which I'm currently learning on the Codecademy platform.
Closes #4612 

Add .discard() method.

---

content/python/concepts/operators/operators.md

Original phrasing was inaccurate and could lead to confusion. The revised explanation clarifies that the `not in` operator returns True when the element isn't found in the iterable and False when it is.
Closes #5018 

Fixed inaccurate explanation of the `not in` operator

---

content/pytorch/concepts/tensors/terms/empty/empty.md

Description
Adding new entry on the .arange() term under PyTorch Tensors concept. It is under docs/content/pytorch/concepts/tensors/terms/empty/empty.md
Issue Solved
Addresses issue: https://github.com/Codecademy/docs/issues/5303
Type of Change
Adding a new entry
Checklist
[x ] All writings are my own.
[x ] My entry follows the Codecademy Docs style guide.
[x ] My changes generate no new warnings.
[x ] I have performed a self-review of my own writing and code.
[x ] I have checked my entry and corrected any misspellings.
[x ] I have made corresponding changes to the documentation if needed.
[x ] I have confirmed my changes are not being pushed from my forked main branch.
[x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
[x ] I have linked any …

[Term Entry] Adding Pytorch Tensor empty

---

content/css/concepts/position/terms/left/left.md

The URLs for the images contained parentheses, causing the links to break during formatting with yarn format.
Fix: The parentheses in the URLs were replaced with their encoded equivalents, %28 for ( and %29 for ), to ensure the links work correctly during formatting.
**Original:**
```markdown
```
**Encoded:**
```markdown
```
Closes #5453

fixed broken images links

---

content/pytorch/concepts/nn/terms/loss-functions/loss-functions.md
content/pytorch/concepts/tensors/terms/view/view.md

A new term entry about the .view() method for Tensors.
#5063
- [ ✅] All writings are my own.
- [✅ ] My entry follows the Codecademy Docs style guide.
- [ ✅] My changes generate no new warnings.
- [ ✅] I have performed a self-review of my own writing and code.
- [ ✅] I have checked my entry and corrected any misspellings.
- [ ✅] I have made corresponding changes to the documentation if needed.
- [✅ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ✅] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [✅ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

[Term Entry]Py torch tensors .view()

---

content/kotlin/concepts/arrays/terms/size/size.md

Added a new term entry on the `.size` property in Kotlin.
Closes #5318

[Term Entry] Kotlin Arrays: .size

---

content/pytorch/concepts/tensor-operations/terms/nonzero/nonzero.md

Added a Term Entry PyTorch Tensor Operations: .nonzero()
Closes #5757 

[Term Entry] PyTorch Tensor Operations: .nonzero()

---

.github/scripts/validate-content-tree.js
.github/workflows/push.yml
package.json

This is meant to prevent "orphaned" docs such as a terms where the parent concept does not have an md file.
Rather than checking for that specifically, we can more generally check to make sure that every folder for a topic/concept/term contains an md file with the same name.
Even after this is merged, it won't be required-for-merge until we add it as a required check in the repo's settings: (`Settings` -> `Branches` -> `main` -> `Edit` -> `Status checks that are required`)

Check to verify that there are not missing md files

---

content/scipy/concepts/scipy-stats/terms/descriptive-stats/descriptive-stats.md

Added a new term entry on `Descriptive Stats` in SciPy.
Closes #5855

[Term Entry] Python:SciPy scipy.stats: Descriptive Stats

---

content/general/concepts/machine-learning/machine-learning.md

Added a new concept entry in general for Machine Learning
Closes #6066 

[Concept Entry] general: Machine Learning

---

content/pytorch/concepts/optimizers/terms/adam/adam.md

Added a new term entry on `Adam` in PyTorch.
Closes #5858 

[Term Entry] PyTorch Optimizers: Adam

---

content/pytorch/concepts/tensor-operations/terms/is-tensor/is-tensor.md

Added a new term entry on `.is_tensor()` in PyTorch.
Closes #6068 

[Term Entry] PyTorch Tensor Operations: .is_tensor()

---

content/pytorch/concepts/tensor-operations/terms/from-numpy/from-numpy.md

Added a .from_numpy() function reference in PyTorch docs, covering its usage, syntax, and memory-sharing behavior between NumPy arrays and tensors. The update makes PyTorch documentation clear and complete.
Closes #6099
Adding a new entry

Contributed .from_numpy() Reference in PyTorch Docs

---

content/javascript/concepts/event-handling/event-handling.md
documentation/tags.md

Added a new Concept Entry for JS: Event Handling
Closes #6170 

Added a new Concept Entry for JS: Event Handling

---

content/pytorch/concepts/tensor-operations/terms/as-strided/as-strided.md

Added a Term Entry for PyTorch Tensor Operations: `.as_strided()`
Closes #6098 

[Term Entry] PyTorch Tensor Operations: `.as_strided()`

---

content/numpy/concepts/built-in-functions/terms/split/split.md

Introduce a new term entry on the .split() under built-in functions in NumPy. 
Created file: docs/content/numpy/concepts/built-in-functions/terms/split/split.md
Closes #6421 
New Term for Existing Concept Entry

[Term Entry] Numpy - split()

---

content/css/concepts/position/position.md

Fixed a typo in the CSS `position` property description in `position.md`. Removed the repeated "or".
no issues
- Editing an existing entry (fixing a typo)

Fix typo in position property list (removed extra 'or')

---

content/c/concepts/arrays/arrays.md

Edited the existing concept entry on `Arrays` in C.
Closes #7053 

[Edit] C: Arrays

---

content/java/concepts/strings/strings.md

Edited the existing concept entry on `Strings` in Java.
Closes #7052 

[Edit] Java: Strings

---

content/java/concepts/array-list/terms/set/set.md

Edited the existing term entry on `.set()` in Java.
Closes #7058 

[Edit] Java: .set()

---

content/python/concepts/keywords/terms/try/try.md

👋 Hi, thanks for submitting a PR to Codecademy Docs! 💖
Please fill out all fields below to ensure your PR is reviewed quickly.
This PR adds a new entry for the Python keyword `try` under:
content/python/concepts/keywords/terms/try/try.md
It includes:
- A definition
- Syntax section
- Example with explanation
- Codebyte block (Python)
This follows the structure described in the Codecademy Docs term entry template and content standards.
#6971

Add keyword entry: try (Python)

---

content/python/concepts/keywords/terms/break/break.md

Added new Python keyword term: break. Created break folder at ./content/python/keywords/terms/break.
Created a new file in that location break.md
Closes Issue #6962

[Term Entry] Python Keyword: break #6962

---

content/python/concepts/keywords/terms/continue/continue.md

Added a new `continue` folder with the `continue.md` entry that documents the Python `continue` keyword. The entry includes a detailed description, syntax section, a simple while-loop example, and a CodeByte example demonstrating how to use `continue` to skip loop iterations.
Closes #6963 

[Term entry]: Python keywords: continue

---

content/python/concepts/strings/terms/replace/replace.md

Edited the existing term entry on `.replace()` in Python.
Closes #7059 

[Edit] Python: .replace()

---

content/cpp/concepts/strings/terms/swap/swap.md

I added a new entry for swap() method under strings in C++. The entry is in content/cpp/concepts/strings/terms/swap/swap.md
Motivation : I am new to open source and I want to become an active open source contributor by adding value wherever I can and always learning new things!
Closes #7134 
- [✅] All writings are my own.
- [✅] My entry follows the Codecademy Docs style guide.
- [✅] My changes generate no new warnings.
- [✅] I have performed a self-review of my own writing and code.
- [✅] I have checked my entry and corrected any misspellings.
- [✅] I have made corresponding changes to the documentation if needed.
- [✅] I have confirmed my changes are not being pushed from my forked `main` branch.
- [✅] I have confirmed that I'm pushing from a new branch named after …

Closes #7134 : Added a new entry for swap() method under strings in C++.

---

content/python/concepts/built-in-functions/terms/len/len.md

[Edit]: Python `len()`
Closes #7228 

[Edit]: Python `len()`

---

content/python/concepts/built-in-functions/terms/next/next.md

Edited the existing term entry on `next()` in Python.

[Edit] Python Built-in Functions: next()

---

content/pandas/concepts/dataframe/terms/sortvalues/sortvalues.md

Edited the existing term entry on `.sort_values()` in Pandas.

[Edit] Pandas: .sort_values()

---

content/java/concepts/strings/terms/compareTo/compareTo.md

Edited the existing term entry on `.compareTo()` in Java.

[Edit] Java Strings: .compareTo()

---

content/pytorch/concepts/tensors/terms/mean/mean.md

Edited the existing term entry on `.mean()` in PyTorch.

[Edit] PyTorch: .mean()
