content/python/encyclopedia/replace-in-python.md, content/python/encyclopedia/strings-in-python.md
Encyclopedia entry for the replace() method in Python
=> replace-in-python

content/language-agnostic/encyclopedia/what-is-an-api.md
Pushing API article. If the CLI issue is still happening let me know. I opened up a github ticket and they instructed me to go to the issues section of the tool which it seems has many people facing the issue that we have with it asking me to sign again after I already did. Anyway let me know if you need any changes to the API article :))
=> Pushing API article 

content/c++/encyclopedia/exceptions-in-cpp.md, content/git/encyclopedia/what-is-push-in-git.md, documentation/tags.md
Here are the two entries I completed. 
I'm sure we'll talk about this, but in the What is Git Pull, I included a section on how to complete one and what could happen when it goes wrong. I found it hard to avoid first/second person pronouns when describing the process the reader might take.
Best,
Matt!
=> completing takehome with two new entires

content/c++/hub-page-info.md, content/css/hub-page-info.md, content/git/hub-page-info.md, content/html/hub-page-info.md, content/java/hub-page-info.md, content/javascript/hub-page-info.md, content/python/hub-page-info.md, content/sql/hub-page-info.md, content/swift/hub-page-info.md, documentation/hub-page-info-template.md
Added hub pages info for all the existing languages.
=> Add hub pages

content/html/glossaries/tags/blockquote.md, content/html/glossaries/tags/br.md, content/html/glossaries/tags/button.md, content/html/glossaries/tags/canvas.md
Adds `blockquote`, `br`, `button`, and `canvas` elements.
=> first batch

content/javascript/concepts/array-methods/pop.md
=> Add JS array method pop

content/javascript/concepts/string-methods/length.md, content/javascript/concepts/string-methods/startsWith.md, content/javascript/concepts/string-methods/trim.md
Added `trim()`, `length`, and `startsWith()` to `string-methods` folder.
=> Add methods trim, length, startsWith

content/javascript/concepts/string-methods/concat.md, content/javascript/concepts/string-methods/repeat.md, content/javascript/concepts/string-methods/substring.md
Added `repeat()`, `substring()` and `concat()` to `string-methods` folder.
=> Add repeat, substring, concat

content/javascript/concepts/date-methods/getDate.md, content/javascript/concepts/date-methods/getDay.md, content/javascript/concepts/date-methods/getHours.md, content/javascript/concepts/date-methods/getMinutes.md, content/javascript/concepts/date-methods/getMonth.md, content/javascript/concepts/date-methods/getSeconds.md
Created a new file called `date-methods` and added `getDate()`, `getDay()` and `getHours()` methods.
=> Add date methods

content/sql/concepts/window-functions-in-sql.md
Created an example-heavy entry on SQL window functions
=> Add encyclopedia entry on SQL window functions

content/sql/concepts/commands/is-not-null.md, content/sql/concepts/commands/is-null.md
Created glossary entries for IS NULL and IS NOT NULL based on the existing WHERE entry. Grouped both entries into one PR as the are practically identical.
=> Add glossary entries for SQL IS NULL and IS NOT NULL

content/language-agnostic/concepts/what-is-a-cache.md, content/language-agnostic/concepts/what-is-bootstrap.md, content/language-agnostic/concepts/what-is-moores-law.md, content/language-agnostic/concepts/what-is-object-oriented-programming.md, content/python/concepts/what-is-a-dictionary.md
what-is-moores-law.md
what-is-bootstrap.md
what-is-a-cache.md
what-is-object-oriented-programming-law.md
what-is-a-dictionary.md
Do let me know if you have any feedback or changes you want me to make. More articles coming :))
=> 5 articles added

content/css/concepts/grids/grid-auto-columns.md, content/css/concepts/grids/grid-auto-rows.md, content/css/concepts/grids/grid-template-rows.md
=> Revert "Revert "new css grid content""

content/language-agnostic/concepts/what-is-git/what-is-git.md
Added a .md file that explains what Git is. There are some code examples included.
=> created what-is-git.md file

content/javascript/concepts/hoisting-in-javascript/hoisting-in-javascript.md
Created an entry, "Hoisting in JavaScript".
=> created entry for JavaScript section

content/css/concepts/typography/font-family.md, content/css/concepts/typography/font-size.md, content/css/concepts/typography/font-style.md, content/css/concepts/typography/font-weight.md, content/css/concepts/typography/letter-spacing.md, content/css/concepts/typography/line-height.md, content/css/concepts/typography/text-align.md, content/css/concepts/typography/text-decoration.md, content/css/concepts/typography/word-spacing.md
Created a new folder named `typography` and added CSS typography:
=> CSS typography

content/css/concepts/transform-functions/rotate.md, content/css/concepts/transform-functions/scale.md, content/css/concepts/transform-functions/skew.md, content/css/concepts/transform-functions/translate.md
`skew()`,
`translate()`,
`rotate()`,
`scale()`
=> Add transform-functions folder and properties

content/language-agnostic/concepts/what-is-a-processor/what-is-a-processor.md, content/language-agnostic/concepts/what-is-a-server/what-is-a-server.md, content/language-agnostic/concepts/what-is-an-algorithm/what-is-an-algorithm.md, content/language-agnostic/concepts/what-is-ram/what-is-ram.md, content/language-agnostic/concepts/what-is-ssl/what-is-ssl.md
What is a Processor?
What is RAM?
What is SSL?
What is an Algorithm?
What is a Server?
=> 5 Artciles added

content/css/concepts/typography/terms/@font-face/@font-face.md, content/css/concepts/typography/terms/text-shadow/text-shadow.md, content/css/concepts/typography/terms/text-transform/text-transform.md
text-shadow, text-transform, @font-face
=> text-shadow, text-transform, @font-face

content/html/concepts/videos-in-html/videos-in-html.md
Another wordy article on best practices for video in HTML
=> Create encyclopedia entry on general use of videos in HTML

content/general/concepts/who-is-ada-lovelace/who-is-ada-lovelace.md, content/general/concepts/who-is-alan-turing/who-is-alan-turing.md, content/general/concepts/who-is-ken-thompson/who-is-ken-thompson.md
Created a collection of biographies for Ada Lovelace, Alan Turing, and Ken Thompson based on existing entries.
=> Create a collection of biographies

.circleci/config.yml, content.test.ts
Slightly messed up the circleci config! Everything else passed though
=> prettier -> format

content/ruby/concepts/casting/casting.md, content/ruby/concepts/dates/dates.md, content/ruby/concepts/gems/gems.md, content/ruby/concepts/inheritance/inheritance.md, content/ruby/concepts/lambda/lambda.md, content/ruby/concepts/regex/regex.md, content/ruby/concepts/scope/scope.md, content/ruby/concepts/sets/sets.md
Please include a summary of the change, such as which topic(s) and file(s). Please also include relevant motivation and context.
Adding the following entries for Ruby:
- Casting
- Dates
- Gems
- Inheritance
- Lambda
- RegEx
- Scope
- Sets
Please delete options that are not relevant.
=> Ruby entries

content/general/concepts/what-is-svg/what-is-svg.md
Create an ecyclopedia entry on "What is SVG".
**NOTE: This was marked as important for SEO so I am unsure what additional work or review may be necessary**
Please delete options that are not relevant.
=> Create encyclopdia entry on What is SVG

content/css/concepts/transition/terms/transition-delay/transition-delay.md, content/css/concepts/transition/terms/transition-duration/transition-duration.md, content/css/concepts/transition/terms/transition/transition.md
- Created new folder for CSS **transition** topic
- Created entries for:
- transition
- transiton-delay
- transition-duration
=> Entries for CSS transition topic

content/css/concepts/transform-functions/terms/transition/terms/transition-property/transition-property.md, content/css/concepts/transform-functions/terms/transition/terms/transition-timing-function/transition-timing-function.md
- Created new folder for CSS **transition** topic
- Created entries for:
- transiton-property
- transition-timing-function
=> CSS transition entries

content/css/concepts/transform-functions/terms/transform-origin/transform-origin.md, content/css/concepts/transform-functions/terms/transform-style/transform-style.md, content/css/concepts/transform-functions/terms/transform/transform.md
Created entries for CSS transform topic
=> CSS transform entries

content/general/concepts/what-is-csv/what-is-csv.md
Create an ecyclopedia entry on "What is CSV".
**NOTE: This was marked as important for SEO so I am unsure what additional work or review may be necessary**
=> Create encyclopdia entry on What is CSV

content/python/concepts/regex-in-python/regex.md, content/python/concepts/regex-in-python/terms/digit-class/digit-class.md, content/python/concepts/regex-in-python/terms/findall/findall.md, content/python/concepts/regex-in-python/terms/search/search.md, content/python/concepts/regex-in-python/terms/split/split.md, content/python/concepts/regex-in-python/terms/sub/sub.md
Initial entries for python regex content
=> first regex entries

content/language-agnostic/concepts/what-is-a-bitwise-operator/what-is-a-bitwise-operator.md, content/language-agnostic/concepts/what-is-augmented-reality/what-is-augmented-reality.md, content/language-agnostic/concepts/what-is-encapsulation/what-is-encapsulation.md, content/language-agnostic/concepts/what-is-iot/what-is-iot.md, content/language-agnostic/concepts/what-is-polymorphism/what-is-polymorphism.md
Please include a summary of the change, such as which topic(s) and file(s). Please also include relevant motivation and context.
Added a few more entries for General.
Please delete options that are not relevant.
=> 5 more articles added

content/html/concepts/classes/classes.md, content/html/concepts/headings/headings.md, content/html/concepts/iframes/iframes.md, content/html/concepts/links/links.md, content/html/concepts/paragraphs/paragraphs.md
Added entries for the following HTML topics: 
- Classes
- Headings
- iFrames
- Links
- Paragraphs
Please delete options that are not relevant.
=> build: added 5 HTML entries

content/python/concepts/built-in-functions/terms/ascii/ascii.md
WOOPS don't mind me (this broke the portal-app build)
=> replace backslash descriptions with proper html entities

CONTRIBUTING.md
Please read this document in its entirety, including the Codecademy Contributor Agreement at the bottom. And edit the portion above the horizontal line!
Please include a summary of the change, such as which topic(s) and file(s). Please also include relevant motivation and context:
Please check the boxes that are revelant to this PR:
---
As a Codecademy Contributor, by submitting any "Asset" to Codecademy via GitHub, you agree to the terms of this "Contributor Agreement":
**_Assets & Works for Hire._** All Assets created and submitted by you are deemed "works made for hire" as that term is defined in the United States Copyright Act and are the sole property of Codecademy. To the extent that ownership of any Asset does not by operation of law vest in Codecademy, you hereby assign to …
=> typo fix in contribution guide

PULL_REQUEST_TEMPLATE.md
=> comment out some PR template boilerplate

content/sql/concepts/commands/terms/inner-join/inner-join.md, content/sql/concepts/commands/terms/outer-join/outer-join.md, content/sql/concepts/commands/terms/select-distinct/select-distinct.md, content/sql/concepts/constraints/constraints.md, content/sql/concepts/primary-keys/primary-keys.md
Fixed minor typos in a couple of entries in the SQL category. The content in the SELECT DISTINCT entry is correct, but the title of the entry (and its references on other pages) was incorrectly titled SELECT; I've changed it to SELECT DISTINCT in the [entry file](content/sql/concepts/commands/terms/select-distinct/select-distinct.md), not sure if it has to be changed elsewhere.
=> Fix SQL entry typos

README.md
* Don't use words like "just" and "simple" in docs; it's unintentionally mean to folks who wouldn't find things just simple
* Links should have descriptive alt text so that screenreaders can narrate them well as a user <kbd>Tab</kbd>s through the page
=> README.md accessibility touchups: language and link alts

content/git/concepts/commit/commit.md, content/git/concepts/init/init.md, content/git/concepts/merge/merge.md, content/git/concepts/pull/pull.md, content/git/concepts/push/push.md
Added missing command line prompts (`$`), changed any references of `master` to `main`, and minor sentence edits.
=> Edit Git entries

content/c/c.md, content/c/concepts/basic-output/basic-output, content/c/concepts/functions/functions.md, content/c/concepts/variables/variables.md, documentation/tags.md
Added C content section along with 4 entries
c.md, 
basic-output.md, 
functions.md, 
and variables.md.
Also added Output to tags.md
=> Add c content

content/javascript/concepts/arrays/terms/slice/slice.md, content/javascript/concepts/arrays/terms/splice/splice.md
- Updated the section on Javascript > Array.splice() to include a note about using a negative start index. 
- Updated phrasing where I felt it was inconsistent with the method (namely, 'remove' instead of 'delete'). 
- Updated other parts of the Syntax section to be internally consistent. 
- Added backticks around references to arguments within their descriptions. 
- I used line 35 of Javascript > Array.slice() as a reference for that decision. I feel that it adds clarity to those references, personally. 
- Should probably make sure that convention is documented and implemented consistently one way or the other.
- A few other minor phrasing/language updates.
=> Negative Start Value - JS Splice

content/html/concepts/semantic-html/terms/figcaption/figcaption.md, content/html/concepts/semantic-html/terms/figure/figure.md, content/html/concepts/semantic-html/terms/footer/footer.md
- [ #] Adding a new entry
- [# ] Editing an existing entry (fixing a typo, bug, issues, etc)
- [# ] Updating the documentation
- [# ] My entry follows the Codecademy Docs style guide
- [# ] I have performed a self-review of my own writing and code
- [ #] I have made corresponding changes to the documentation
- [# ] My changes generate no new warnings
- [ #] I have checked my entry and corrected any misspellings
- [ #] All writings are my own
I corrected some misspellings and typo
=> Fix grammar

content/javascript/concepts/data-types/data-types.md
BigInt was recently added to the ECMAScript standard and can be found in the [11th edition](https://262.ecma-international.org/11.0/#sec-ecmascript-language-types-bigint-type) of the published standard. The BigInt data type has also been supported by [major browsers and NodeJS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#browser_compatibility).
- [✅] Updating the documentation
- [✅] My entry follows the Codecademy Docs style guide
- [✅] I have performed a self-review of my own writing and code
- [✅] I have made corresponding changes to the documentation
- [✅] My changes generate no new warnings
- [✅] I have checked my entry and corrected any misspellings
- [✅] All writings are my own
=> ADD: BigInt data type documentation

content/html/concepts/lists/lists.md
- Added nesting list elements in html.
=> add nesting a list in html

content/c/concepts/pointers/pointers.md
- Added an entry about pointers in the C language
=> Add entry for pointers to C content

content/javascript/concepts/modules/modules.md, content/javascript/concepts/requests/requests.md
- Added entry for Javascript Modules.
- Added entry for Javascript Requests.
=> Added Javascript entries for Modules and Requests

content/python/concepts/data-types/data-types.md, content/python/concepts/sets/sets.md
I created a new entry for Python sets. This entry was requested at https://github.com/Codecademy/docs/issues/182. 
The Data Types entry for the Python docs currently only mentions the `type()` function. I've added an explanation of the `isinstance()` function to the entry since it is one of the most widely used methods for testing type. I've also changed the header for the `type()` function to lowercase to match the style guidelines. 
=> add isinstance() built-in function to data types entry and create new entry for python sets

content/cpp/concepts/files/files.md
=> added entry for files in cpp docs

content/javascript/concepts/arrays/terms/filter/filter.md
Adding a .filter() method to javascript arrays directory. I created a filter.md file with a brief description and 3 examples showcasing each parameter option in use. I wanted to give back to Codecademy by contributing an important javascript array method. 
=> adding .filter() to javascript/concepts/arrays/terms

content/cpp/concepts/pointers/pointers.md
- Added entry for C++ Pointers.
=> added entry for cpp pointers

content/emojicode/concepts/comments/comments.md, content/emojicode/concepts/conditionals/conditionals.md, content/emojicode/concepts/data-types/data-types.md, content/emojicode/concepts/dictionaries/dictionaries.md, content/emojicode/concepts/hello-world/hello-world.md, content/emojicode/concepts/interpolation/interpolation.md
=> Revert "nothing to see here"

content/sql/concepts/commands/terms/inner-join/inner-join.md, content/sql/concepts/commands/terms/outer-join/outer-join.md, content/sql/concepts/commands/terms/select/select.md
Made a few small typo corrections to the sql content commands files, specifically, inner join, outer join, and select. Not all tests are currently passing, would love some guidance on how to correct that.
=> SQL Command Typo Corrections

CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md
updates contribution guide and PR template with test failure remediation tips; also commented out the `Codecademy Username` section of the PR template
=> update docs and PR template to aid test failure resolution

content/general/concepts/what-is-git/what-is-git.md
I have edited the description entry for `content/general/content/what-is-git/`, as mentioned on issue [https://github.com/Codecademy/docs/issues/243](https://github.com/Codecademy/docs/issues/243), making it close to the goal of 150 characters.
=> (Fix) Edited what-is-git description entry

content/general/concepts/what-is-node-js/what-is-node-js.md
It would be better to stick to "JavaScript" instead of its abbreviation which is "JS" so that everyone is clear about what they're reading & it's more concise.
=>  Rename "JS" to "JavaScript"

content/javascript/concepts/arrays/arrays.md
=> edit javascript array entry code snippet

content/javascript/concepts/arrays/terms/filter/filter.md
=> remove word from js filter method note

content/javascript/concepts/arrays/terms/map/map.md
=> edit javascript array map method punctuation format to match other array methods

content/javascript/concepts/arrays/terms/isArray/isArray.md
=> edit javascript isArray method description and note

.github/ISSUE_TEMPLATE.md, content/java/concepts/arrays/arrays.md, content/java/concepts/classes/classes.md, content/java/concepts/conditionals/conditionals.md, content/java/concepts/enums/enums.md, content/java/concepts/loops/loops.md, content/java/concepts/math-methods/math-methods.md, content/java/concepts/math-methods/terms/abs/abs.md, content/java/concepts/math-methods/terms/acos/acos.md, content/java/concepts/math-methods/terms/atan2/atan2.md, content/java/concepts/strings/strings.md, content/java/concepts/strings/terms/codePointCount/codePointCount.md, content/java/concepts/strings/terms/concat/concat.md
Reviewed all the existing articles in the Java section and updated them to fix typos, improve sentence flow, and use more correct terminology. Also added a section in the Loops article for `for` loops which was previously missing (some of this content came from the Learn Java course on CC).
=> Review and edit all existing Java articles

content/markdown/concepts/blockquotes/blockquotes.md
=> Edit blockquote md

content/react/concepts/components/components.md
=> updated typo

content/general/concepts/what-is-an-object/what-is-an-object.md
Adding "What is Object" entry for General.
=> add 'what-is-an-object'

.github/workflows/concept-of-the-week.yml
auto-update action failed cause no gh user was being set (I had a feeling this would happen!)
using codecademydev now (as we do in client-modules)
- infra
=> set gh user before staging files

.github/workflows/push.yml
Following up on https://github.com/Codecademy/docs/pull/407, @jakemhiller is helping me with GHA.
=> Add on: pull_request: to Push GHA workflow

content/general/concepts/what-is-next-js/what-is-next-js.md
I'm actually testing to see how GitHub Actions works 🥇 Fixes issue #231. 
=> Entry Edit: General - Next.js (GH Actions Test)

README.md
He doesn't work here anymore 😢
=> Remove Li from Engineering Team list

.github/ISSUE_TEMPLATE/bug_reports.yml, .github/ISSUE_TEMPLATE/entry_edit.yml, .github/ISSUE_TEMPLATE/entry_request.yml
Changed language in the `ISSUE_TEMPLATE` forms for _single entries/terms only_.
=> Edit issue forms

.github/PULL_REQUEST_TEMPLATE.md
@sonnynomnom @yangc95 What do we think about this?
=> refactor: moved language about add GitHub profile to top of file.

content/react/concepts/routing/routing.md
The library React Router has been changed, and with it comes breaking changes. Since the official tutorial has been changed I updated the codeblock to v6
Closes Issue #444 
=> Updated React Router Codeblock to v6

content/css/concepts/animations/animations.md
Added description to what the example code does: change from yellow to orange over 5 seconds
fix: Added that the animation duration must be defined for the animation to work.
Explaining what the example code does is helpful for learning!
=> Describe what code does and minor fix

content/javascript/concepts/functions/functions.md
Changed the name of `add()` to `sum()`
=> Changing names of functions

documentation/entry-template.md, documentation/term-entry-template.md, documentation/topic-info-template.md
In response to previous discussions, I went ahead and added new language to the comments for the meta-`Descriptions`s in the templates for:
- Regular Entries
- Term Entries
- Topic Info Entries
=> [Edit]: New criteria comments for entry templates

content/html/concepts/images/images.md
- Editing an existing entry (fixing a typo)
=> HTML Images: Updated typo

documentation/tags.md
Add `NFT` and `Blockchain` as a part of tags.
=> Add new tags

content/c/c.md, content/c/concepts/arrays/arrays.md, content/c/concepts/basic-output/basic-output.md, content/c/concepts/comments/comments.md, content/c/concepts/compiling/compiling.md, content/c/concepts/functions/functions.md, content/c/concepts/memory-management/memory-management.md, content/c/concepts/pointers/pointers.md, content/c/concepts/strings/strings.md, content/c/concepts/strings/terms/strchr/strchr.md, content/c/concepts/strings/terms/strcmp/strcmp.md, content/c/concepts/strings/terms/strcpy/strcpy.md, content/c/concepts/strings/terms/strlen/strlen.md, content/c/concepts/user-input/user-input.md, content/c/concepts/variables/variables.md
=> c-plus-plus -> c, occurrence spelling in strings

.github/ISSUE_TEMPLATE/bug_reports.yml, .github/ISSUE_TEMPLATE/entry_edit.yml, .github/ISSUE_TEMPLATE/entry_request.yml
Wanted to make a few edits to our issue templates in `.github/ISSUE_TEMPLATE/` for better clarity and enhanced usability, including: 
- Adding an optional text area for the new entry issue template in `entry_request.yml`.
- Changing language to distinguish a "Topic" entry (ex: [HTML](https://github.com/Codecademy/docs/blob/main/content/html/html.md)), a "Concept" entry (ex: [HTML: Tags](https://github.com/Codecademy/docs/blob/main/content/html/concepts/tags/tags.md)), and a "Term" entry (ex: [HTML: Tags: Blockquote](https://github.com/Codecademy/docs/blob/main/content/html/concepts/tags/terms/blockquote/blockquote.md)).
=> Edits to Issue templates

content/javascript/concepts/sets/sets.md
Edit metadata from singular to plural form (noticed after merge)
=> Edit metadata

content/python/concepts/strings/terms/find/find.md
Added that the `find()` method is case-sensitive.
=> Adding a small important detail

content/javascript/concepts/map/map.md
Sticking with single-quotes in the codebyte example to stay consistent with rest of entry. Also linking around the term entries, per [a recent suggestion by Steve](https://github.com/Codecademy/docs/pull/494/files#r776844210).
=> Update JavaScript map.md

content/general/concepts/modulo/modulo.md
=> Create General/Modulo resolves 338

content/cpp/concepts/constructors/constructors.md
Created a new entry for C++ constructors: docs/content/cpp/concepts/constructors/constructors.md
=> C++ constructors, resolves #298

content/general/concepts/open-source/open-source.md
Add general topic "open source"
=> Open source - Resolves 336

content/python/concepts/inheritance/inheritance.md
Language: Python
File: python/concepts/inheritance/inheritance.md
Edited File: inheritance .md
Under the "Abstract Base Class" heading in inheritance.md, I noticed references to an 'Employee' class that does not exist. I corrected these references to the intended class, 'AbstractClass', and reworked the explanation to make it a bit more clear.
=> Update ABC explanation in inheritance.md

.github/ISSUE_TEMPLATE/bug_reports.yml, .github/ISSUE_TEMPLATE/entry_edit.yml, .github/ISSUE_TEMPLATE/entry_request.yml
Made it so when you make an issue you are not required to check the labels added box because most people that make issues don't have access to adding them.
=> Fixed issue templates

.github/CONTRIBUTING.md
=> [Edit] Documentation: Contribution Guide 

content/go/concepts/switch/switch.md
For Codebyte snippet signatures, the programming language is usually spelled differently compared to a regular snippet.
Some examples:
\```codebyte/python vs. \```py
```codebyte/javascript vs. \```js
```codebyte/golang vs. \```go
=> [Edit] Go: Switch - Revised Codebyte signature

documentation/content-standards.md
For Codebyte snippet signatures, the programming language is usually spelled differently compared to a regular snippet.
Some examples:
\```py vs. \```codebyte/python
\```js vs. ```codebyte/javascript
\```go vs. ```codebyte/golang 
The changes were informed by [the `client-modules` repo file on Codebyte consts](https://github.com/Codecademy/client-modules/blob/main/packages/codebytes/src/consts.ts) and were styled after [the code block standards](http://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/#code-blocks) in the Markdown Style Guide.
=> Updated Codebyte section in Content Standards

content/html/concepts/tags/terms/q/q.md
Replaced relative path image link with direct, raw content URL to the same image.
=> Fix image render in `q.md` entry

content/git/concepts/add/add.md, content/git/concepts/branch/branch.md, content/git/concepts/clone/clone.md, content/git/concepts/commit/commit.md, content/git/concepts/init/init.md, content/git/concepts/merge/merge.md, content/git/concepts/pull-requests/pull-requests.md, content/git/concepts/pull/pull.md, content/git/concepts/push/push.md, content/git/concepts/reset/reset.md, content/git/concepts/status/status.md
Closes #538 
Update incorrect, incomplete or unclear areas in the Git content.
Change some first and second person language to the third person as requested here:
https://github.com/Codecademy/docs/issues/538#issuecomment-1039460169
- Editing existing entries (fixing a typo, bug, issues, etc)
=> Edits to Git entries (11 total)

content/general/concepts/front-end/front-end.md
@sonnynomnom once you approve I can merge.
=> Add Entry - General: Front-End 

.github/PULL_REQUEST_TEMPLATE.md
Added another checkbox for linking relevant issues.
=> PR checkbox for linking issues

content/html/concepts/tags/terms/center/center.md, documentation/tags.md
Add term entry for the HTML center tag. Prompted by the target keyword list.
=> Add Term Entry - HTML <center>

content/html/concepts/images/images.md
Linking [`<img>`](https://www.codecademy.com/resources/docs/html/tags/img) tag and adding keywords
=> Edit HTML images

content/general/concepts/proxy-server/proxy-server.md
Just a quick PR that edits the meta-`Title` to following file-folder naming conventions.
=> Edited meta-Title to match file/folder structure

content/python/concepts/built-in-functions/terms/filter/filter.md
Added a `print()` line to the Codebyte snippet so readers can view the results after pressing "Run".
=> Edit: Added `print()` to Codebyte

content/css/concepts/floats/floats.md
Fixed a wrong image link making the image not display.
=> Fixed wrong image link

content/javascript/concepts/memoization/memoization.md
Super-small edit to `javascript/memoization.md`.
=> JS: Memoization grammar fix

content/general/concepts/vim/vim.md
Every entrance must have an exit!
=> Found a Way Out of Vim 🧙 

content/python/concepts/files/files.md
Noticed an extra parenthesis after link 😮
- Editing an existing entry (fixing a typo)
=> Python Files typo

documentation/tags.md
Added the `ux` tag to the list of possible tags.
=> Added `ux` tag

content/java/concepts/hashmap/hashmap.md, content/java/concepts/queue/queue.md, content/java/concepts/treemap/treemap.md
=> Java: Queue Edit

content/general/concepts/github/github.md
Added the general entry for Github.
Closes #717 
=> [Entry] General: Github

content/cpp/concepts/maps/terms/erase/erase.md
Fixing C++ maps | .erase() entry last example to be a codebyte as stated.
=> Edit C++ Maps .erase() entry

.github/CONTRIBUTING.md
Changed the link to the CC doc category of the forums.
=> Fixed a link

content/cpp/concepts/structure/structure.md
=> Edit C++ Structure (typo only)

content/html/concepts/tags/terms/video/video.md
=> Fix <video> tag in `video.md`

.github/CONTRIBUTING.md
=> modified CONTRIBUTING.md

content/general/concepts/json/json.md
Update inspired from information from this [Codecademy article](https://www.codecademy.com/article/what-is-json) with similar content.
=> Update General: JSON

content/uiux/concepts/information-architecture/information-architecture.md, content/uiux/concepts/site-map/site-map.md, content/uiux/concepts/user-workflows/user-workflows.md
Spotted some images in the new UIUX entries that are SVGs, which are causing the rendering to be not amazing contrast. I changed them to the png file in the same location. Should be a quick merge.
=> Change image format

README.md
Docs has crossed another milestone! Over the weekend, its 1,000th new entry was published; Docs is barely a year old! 🚀 🙌🏻 🌟
I updated the count in `README.md` but feel free to suggest anything else in this PR 😄 
=> Update number of published, live entries

.github/CONTRIBUTING.md
Add bullet point about PRs (that don't meet basic structure/criteria for review) will be removed from the queue after 2 weeks of no consistent effort for improving. For example, a PR that is mainly plagiarized and the contributor is unresponsive. Other issues may be a file that is submitted in another type of encrypted file or format that's not the standard format.
Not to deter contributors from making mistakes, questions are always welcome
=> Edit Contribution Guide

README.md
Updating with link to new feedback form for Codecademy Docs.
=> Update README.md w/ new feedback form

content/html/concepts/accessibility/accessibility.md, content/html/concepts/accessibility/terms/aria-attributes/aria-attributes.md, content/html/concepts/accessibility/terms/aria-attributes/terms/aria-label/aria-label.md
=> add A11y HTML concept

content/general/concepts/wsdl/wsdl.md
=> New Entry: General WSDL

content/javascript/concepts/iterators/iterators.md, content/javascript/concepts/sets/sets.md, content/javascript/concepts/sets/terms/add/add.md, content/javascript/concepts/sets/terms/clear/clear.md, content/javascript/concepts/sets/terms/delete/delete.md, content/javascript/concepts/sets/terms/has/has.md, content/javascript/concepts/sets/terms/size/size.md
=> Add Terms for JS: Sets; Clean up JS: Iterators

content/java/concepts/interfaces/interfaces.md
=> New Entry: Java Interfaces

content/java/concepts/collection/collection.md, content/java/concepts/collections/collections.md, content/java/concepts/collections/terms/max/max.md, content/java/concepts/collections/terms/min/min.md, content/java/concepts/collections/terms/reverse/reverse.md, content/java/concepts/collections/terms/shuffle/shuffle.md, content/java/concepts/collections/terms/sort/sort.md, content/java/concepts/collections/terms/swap/swap.md
From the Target Keyword List. Should be merged after [#832](https://github.com/Codecademy/docs/pull/832) because it links to Comparator & Comparable.
=> New Entries & Terms: Java Collections & Collection

content/java/concepts/generics/generics.md
=> New Entry: Java Generics

content/sql/concepts/aggregate-functions/terms/sum/sum.md
The existing sentence was probably a copy pasta from the MIN() function page. Just modified it to explain the example.
=> Fix explanation sentence in the SUM() page

content/java/concepts/files/files.md
=> New Entry: Java Files

content/general/concepts/font-awesome/terms/fa-pulse/fa-pulse.md, content/general/concepts/font-awesome/terms/fa-spin/fa-spin.md
=> switched .png with .gif (Gen: Font Awesome)

content/css/concepts/background/terms/background-color/background-color.md, content/html/concepts/elements/terms/applet/applet.md, content/html/concepts/elements/terms/source/source.md, content/html/concepts/forms/forms.md, content/html/concepts/iframes/iframes.md, content/html/concepts/lists/lists.md
=> Fix broken HTML elements links

content/javascript/concepts/jquery/terms/click/click.md, content/javascript/concepts/jquery/terms/dblclick/dblclick.md, content/javascript/concepts/jquery/terms/hide/hide.md, content/javascript/concepts/jquery/terms/html/html.md, content/javascript/concepts/jquery/terms/text/text.md
=> More edits to jQuery terms

content/javascript/concepts/jquery/terms/hide/hide.md
=> Update hide.md  under JS: jQuery

content/javascript/concepts/jquery/terms/show/show.md
=> Update show.md under JS: jQuery

content/general/concepts/one-hot-encoding/one-hot-encoding.md
=> New Entry: General One Hot Encoding

README.md
Adding @HishamT, a fellow CC from Codecademy, to the fold! (Under "Content Team" in `README.md`)
=> Add Hisham to `README.md`

content/c/concepts/memory-management/terms/realloc/realloc.md
=> Add meta-`Description` to `realloc.md` entry

content/java/concepts/errors/terms/stringindexoutofboundsexception/stringindexoutofboundsexception.md, content/java/concepts/stringbuilder/stringbuilder.md, content/java/concepts/stringbuilder/terms/capacity/capacity.md, content/java/concepts/stringbuilder/terms/indexOf/indexOf.md, content/java/concepts/stringbuilder/terms/replace/replace.md, content/java/concepts/variables/variables.md
Just some really small edits to PR #870
=> Edits to Java Stringbuilder

content/c/concepts/strings/strings.md
=> Update Entry: C Strings

content/java/concepts/math-methods/terms/abs/abs.md, content/java/concepts/math-methods/terms/acos/acos.md, content/java/concepts/math-methods/terms/asin/asin.md, content/java/concepts/math-methods/terms/atan/atan.md, content/java/concepts/math-methods/terms/atan2/atan2.md, content/java/concepts/math-methods/terms/random/random.md
From target keyword list, also brought other Math entries in line with current style.
=> New Term: Java `Math.random()`

content/general/concepts/objective-c/objective-c.md
=> Add Entry: General Objective-C

content/cpp/concepts/templates/templates.md
=> New Entry: C++ Templates

content/java/concepts/math-methods/terms/sqrt/sqrt.md
=> Add new Java Math Methods entry: `.sqrt()` method

content/java/concepts/math-methods/terms/pow/pow.md
Created java math-method .pow entry
Closes #909
=> Created java .pow method entry

documentation/tags.md
=> add 'Ethical Hacking' tag

content/java/concepts/compiler/compiler.md
=> New Entry: Java Compiler

content/cpp/concepts/math-functions/terms/sqrt/sqrt.md
Closes #960 
Created folder named sqrt at path : c++/concepts/math-functions/terms/
Created file named sqrt.md, which includes all relevant data for a Term Entry Issue
=> New Entry: C++ Math Functions: `sqrt()`

content/java/concepts/compiler/compiler.md
=> Typo in Java Compiler Entry

content/python/concepts/operators/operators.md
=> Typo in Python Operators

README.md
=> Update eng team

documentation/content-standards.md, documentation/entry-template.md, documentation/term-entry-template.md, documentation/topic-info-template.md
Made some improvements/edits to the [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and entry templates under [documentation](https://github.com/Codecademy/docs/tree/main/documentation). The edits include:
- Clarified instruction for contributors to **bold** the first mention of a topic, concept, or term in an entry file.
- Linking to the content standards where it made sense.
- Linking to template entries when it made sense.
- Reformatting the references to filenames and extensions (from **bold** to `backticks`).
- Added punctuation to a few list items and latin abbreviations.
- Reorganized the "## Codebyte Example" sections in the templates.
- Other small edits.
=> Edit content standards and entry templates

content/cpp/concepts/math-functions/terms/exp/exp.md
=> [Edit] C++ Math Functions: `exp()`

content/general/concepts/cybersecurity/cybersecurity.md
=> Update cybersecurity.md (fix broken URL)

content/pandas/concepts/groupby/terms/sum/sum.md
Fix typos for pandas documentation
=> Fix typos for pandas documentation

content/r/r.md
=> fix typos in r documentation

content/javascript/concepts/ajax/ajax.md, content/javascript/concepts/arrays/terms/join/join.md, content/javascript/concepts/arrow-functions/arrow-functions.md, content/javascript/concepts/map/terms/size/size.md, content/javascript/concepts/npm/npm.md, content/javascript/concepts/number-methods/number-methods.md, content/javascript/concepts/number-methods/terms/toExponential/toExponential.md, content/javascript/concepts/number-methods/terms/toPrecision/toPrecision.md, content/javascript/concepts/promise/terms/allSettled/allSettled.md, content/javascript/concepts/promise/terms/any/any.md, content/javascript/concepts/regexp/regexp.md, content/javascript/concepts/sets/terms/size/size.md, content/javascript/concepts/sort/sort.md, content/javascript/concepts/this/this.md
fix typos in javascript documentation
=> fix typos in javascript documentation

content/cloud-computing/cloud-computing.md, content/cloud-computing/concepts/types-of-cloud/types-of-cloud.md
=> fixed slugs

content/uiux/concepts/stakeholder/stakeholder.md
Add stakeholder markdown file.
=> Add stakeholder

content/swiftui/concepts/views/terms/button/button.md
Some changes are requested by @Dusch4593 in relation to PR #1102 . Implemented those changes in this PR
=> Implemented the requested changes

content/java/concepts/math-methods/terms/next-after/next-after.md
I added the `.nextAfter()` Java Math method in `java/concepts/math-methods/terms/`. The file:
- Defines `.nextAfter()`
- Provides the syntax
- Provides an example
Closes #906 
=> New term entry for .nextAfter()

content/java/concepts/math-methods/terms/nextAfter/nextAfter.md
Fixed a typo
This PR is in response to a comment on #1144 
=> Fixed typo - added a period

content/java/concepts/math-methods/terms/toRadians/toRadians.md
=> add typo to entry on purpose

documentation/content-standards.md
To avoid any confusion with file naming for terms that are in camelCase or PascalCase
=> Edit Content Standards

content/general/concepts/jit-compilation/jit-compilation.md, content/general/concepts/runtime/runtime.md
Minor edits as requested in #1101 
=> Edit JIT Compilation entry

content/javascript/concepts/comments/comments.md
In the JavaScript Comments file the second sentence on line 34, which explains the usage of comments, should be edited to be better understood.
This is the original sentence: "Comments are good ways for a variety of reasons like explaining a code block or indicating some hints, etc."
I removed the word "ways" to improve the grammar.  It now reads: "Comments are good for a variety of reasons like explaining a code block or indicating some hints, etc."
This PR closes issue #1190 that I created before.
Thanks!
=> Fixed a typo found in the JavaScript Comments content on line 34

content/java/concepts/math-methods/terms/cbrt/cbrt.md
Updated the cbrt.md file with a few changes as proposed by @Dusch4593 . This included changing 'cubed root' to 'cube root' and decreasing the spacing on the example code block. I also noticed that the output for the code block did not appear correctly on the website and gave the code block the tag 'shell' similar to the example output in the log.md file.
=> Fix typo and code block formatting for Java -> math_methods -> Math.cbrt()

content/java/concepts/math-methods/terms/log/log.md, content/java/concepts/math-methods/terms/log10/log10.md, content/java/concepts/math-methods/terms/log1p/log1p.md
=> :tada: fix: title changed to `.log()`, `.log10()`, and `.log1p()` (#902)

content/java/concepts/stack/stack.md
Duplicate content in the Stack's methods.
=> Removed duplicate content in the Stack's methods section

content/java/concepts/math-methods/terms/sin/sin.md
=> make a sin method in java

content/cybersecurity/concepts/nmap/terms/nmap-scan/nmap-scan.md
=> Change meta-`Title` to "Title Case"

content/sql/concepts/operators/operators.md
I have added another comparison operator '<>' which is 'Not Equal To' to the Operators Markdown file in the SQL, concepts, operators docs. The comparison operators '<>' and '!=' function the same. 
I think it would be good to mention this in the docs to make users aware in case they come across '<>'.
=> Added another Not Equal To comparison operator

content/go/concepts/map/map.md
=> New pull request for go map.md

content/cloud-computing/concepts/cloud-services/cloud-services.md, content/general/concepts/routing/routing.md
Fixed slugs for free Codecademy courses so that the link renders at the bottom of the entry pages.
=> fix free learn links in CatalogContent

content/go/concepts/map/map.md
Changed subheading for code demonstrating how to save a corresponding value of a key accessed from a map into a variable in map.md for Go. Also added a missing 'This will output" line for this code example. I want to have more experience editing a change that I made on a repository. I also linked my GitHub to Codecademy so I won't be anonymous. This new pull request will ensure I am a contributor on Codecademy Docs.
=> Change one example subheading and added missing line in map.md for Go

content/go/concepts/arrays/arrays.md
I edited the Codebyte Example so that it runs without issues.
=> Fix the Codebyte Example in the Go arrays entry

content/python/concepts/strings/terms/split/split.md
=> Edit Python Strings `.split()`

content/css/concepts/pseudo-classes/pseudo-classes.md
Minor updates to CSS Pseudo Classes as suggested by @Dusch4593.
=> Minor Updates to Pseudo Classes

content/javascript/concepts/ajax/ajax.md
There's a typo in the first sentence, "programmng" should be "programming".
=> [Edit] JavaScript: AJAX (typo)

content/javascript/concepts/ajax/ajax.md
Fixed a typo (the word "utilize") for a project in the Web Dev Skillpath at Codecademy.
=> fix typo (utilize)

documentation/catalog-content.md
In recent months, some new topics were introduced to Docs. This PR aims to add more free and paid course slugs for these topics.
=> Add topic slugs to `catalog-content.md`

content/swiftui/concepts/viewmodifier/terms/underline/underline.md
- Applied minor text corrections
These corrections have been done to the already closed issue #1395
=> Corrected swiftUI term `.underline()`

.github/CONTRIBUTING.md
Updated the git branch link. Just happened to notice it didn't work
=> Fix bad link - git branches

content/cpp/concepts/functions/functions.md
Update and fix typographical errors on cpp-resources `functions.md` file 
=> FIX: update typo

.github/workflows/push.yml
=> Update github actions

content/c-sharp/concepts/math-functions/terms/max/max.md
=> Fix Title on C# Math Functions `.Max()` entry

content/swiftui/concepts/viewmodifier/terms/fontWeight/fontWeight.md, content/swiftui/concepts/viewmodifier/terms/frame/frame.md, content/swiftui/concepts/viewmodifier/terms/overlay/overlay.md, content/swiftui/concepts/viewmodifier/terms/resizable/resizable.md, content/swiftui/concepts/viewmodifier/terms/scaledToFit/scaledToFit.md, content/swiftui/concepts/viewmodifier/terms/tracking/tracking.md, content/swiftui/concepts/viewmodifier/terms/underline/underline.md, content/swiftui/concepts/viewmodifier/viewmodifier.md
=> [Edit] SwiftUI ViewModifier metadata

content/cpp/concepts/stacks/terms/empty/empty.md, content/general/concepts/programming-optimization/programming-optimization.md, content/open-source/concepts/linux-kernel/linux-kernel.md, content/python/concepts/files/files.md, content/r/concepts/csv-files/csv-files.md, content/swiftui/concepts/viewmodifier/terms/overlay/overlay.md
Editing links that incorrectly target 'terms' folder for computer hardware and other misc links
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR …
=> [Edit] Link Corrections 

content/javascript/concepts/arrays/terms/forEach/forEach.md
Edit to fix and add a description to the codebyte example which was just returning `0`. 
=> [Edit]: JavaScript Arrays: forEach()

content/sql/concepts/commands/terms/round/round.md, content/sql/concepts/data-types/data-types.md
A couple of small typos in entries I previously submitted.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).
=> [Edit]: SQL Entry Typos

content/c-sharp/concepts/strings/terms/replace/replace.md
A C# entry has been created for the Strings.Replace() method. This is the first "term" entry for C# Strings, so I have created a new folder labeled "terms" under c-sharp/concepts/strings. Closes https://github.com/Codecademy/docs/issues/1840.
- Adding a new entry.
=> C# Strings.Replace() entry added for review

content/python/concepts/built-in-functions/terms/open/open.md, content/python/concepts/classes/classes.md, content/python/concepts/dunder-methods/dunder-methods.md, content/python/concepts/files/terms/remove/remove.md, content/python/concepts/files/terms/rmdir/rmdir.md, content/python/concepts/files/terms/unlink/unlink.md, content/python/concepts/modules/terms/pyspark/pyspark.md, content/python/concepts/os-path-module/terms/join/join.md, content/python/concepts/requests-module/requests-module.md
Close#<1912> The issue identified some broken links inside Codecademy Docs section dedicated to Phyton's concepts.
Entries (11-13, 15-20) have been fixed by editing the given files with the correct URLs.
*Exception*, the entry# 14 had the follow link to be corrected:
After exploring the code of the relative file and recognized that the given link belongs to a snipped code example as simple text it's clear that doesn't need to be active(follows screenshot).
Let me know if any more changes are need, or how to improve the PR, thank you.
=> Broken links #1912

content/powershell/concepts/arrays/arrays.md, content/powershell/concepts/environment-variables/environment-variables.md, content/powershell/concepts/objects/objects.md, content/powershell/concepts/operators/operators.md, content/powershell/concepts/variables/variables.md, documentation/catalog-content.md, documentation/tags.md
This PR includes content for Arrays, Objects, Operators, and Variables for PowerShell.
- ~~We need to add PowerShell to [subjects.md](https://github.com/Codecademy/docs/blob/main/documentation/subjects.md)~~
- Add `Environment Variables` to [tags.md](https://github.com/Codecademy/docs/blob/main/documentation/tags.md) ✅
- ~~Add PowerShell in "Supported Code Blocks" of [style-guide.md](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#supported-code-blocks)~~
- Add PowerShell to [catalog-content.md](https://github.com/Codecademy/docs/blob/main/documentation/catalog-content.md) ✅
- ~~Not sure about "Code foundations" tag~~
=> Add Arrays, Objects, Operators, Variables content for PowerShell

content/powershell/concepts/conditionals/conditionals.md, content/powershell/concepts/functions/functions.md, content/powershell/concepts/loops/loops.md, documentation/tags.md
This is a better attempt at PR #1786, which I closed. This time I based it on a proper branch.
Adds Conditionals, Functions, and Loops docs for PowerShell as well as three tags: `Break`, `Continue`, and `ForEach`. 
This addition follows a PR that adds arrays, objects, operators, and variables docs #1705. I did my best to apply all the feedback and suggestions I received from that PR.
=> Add PowerShell content: Conditionals, Functions, and Loops

content/matplotlib/concepts/pyplot/terms/hist/hist.md, content/matplotlib/concepts/pyplot/terms/subplots/subplots.md
A pair of path edits for relevant images.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).
=> path edits

content/python/concepts/loops/loops.md
Embed Skillsoft video on python loops. Please watch the video to fact check.
- [ x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the …
=> Python Loops video

content/javascript/concepts/variables/variables.md
Embedded Skillsoft video on JavaScript variables. Can you fact check the video to make sure everything they are saying is correct?
- [ x] Under "Development" on the right, I have linked any issues that are relevant to …
=> JavaScript Variables video

content/css/concepts/flexbox/flexbox.md
I've embedded a video walkthrough on css flexbox
=> Add video to css flexbox

content/general/concepts/data-science/terms/data-warehouse/data-warehouse.md
A new entry under data science that explains what a data warehouse is and how it is constructed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).
=> [Term Entry] Data Science: Data Warehouse

content/css/concepts/selectors/selectors.md
Add Skillsoft video on CSS selectors.
=> CSS Selectors Video

content/css/concepts/padding/padding.md
Add SKIL video on CSS padding.
=> CSS padding video

content/python/concepts/tuples/tuples.md
Add SKIL video for Python tuples. Please watch video to make sure content is up to standard.
- [ x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in …
=> Python tuples video

content/python/concepts/lists/lists.md
Added SKIL video on creating and editing python lists. Please watch video for quality assurance.
- [ x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue …
=> Python list video

content/c-sharp/concepts/enums/enums.md
Doc added to explain enums in C# under `content/c-sharp/concepts/enums/enums.md`
I included examples of an enum both without specific number assignments, along with a codebyte example of using an enum for different log types.
=> add c# enums doc

content/html/concepts/attributes/terms/class/class.md
Fix capitalization on HTML Attribute
=> Fix HTML Attribute Class Title

README.md
- Update content and engineering teams
- Add exceptions for a couple markdownlint rules that shouldn't apply in this case
=> Update content and engineering teams

content/c-sharp/concepts/strings/terms/startswith/startswith.md
docs/content/c-sharp/concepts/strings/terms/startswith/startswith.md
Added new term StartsWith() in c-sharp concept entry. i used endswith.md as a reference, i dont know c-sharp but i used examples from endswith.md and i checked them, they work as intended. If change doesn't get pulled it was a pleasant experience, nonetheless. 
- [+] My entry follows the Codecademy Docs style guide.
- [+] My changes generate no new warnings.
- [+] I have performed a self-review of my own writing and code.
- [+] I have checked my entry and corrected any misspellings.
- [+] I have made corresponding changes to the documentation if needed.
- [+] I have confirmed my changes are not being pushed from my forked `main` branch.
- [+] I have confirmed that I'm …
=> added: startswith.md in csharp\concepts\strings\terms\startswith directory

content/c-sharp/concepts/enums/enums.md
Use `public` for C# enum examples. In the last case, this fixes a broken codebyte.
=> make enum examples use public

content/kotlin/concepts/functions/functions.md
Added SKIL video to the page. Watch video for quality assurance.
=> Kotlin functions video

content/swiftui/concepts/viewmodifier/terms/scaledToFill/scaledToFill.md
Fix metadata typo in `.scaledToFill()` entry.
=> Fix Typo in New `.scaledToFill()` entry

content/javascript/concepts/objects/objects.md
Add SKIL video on JS objects. Watch video through for quality assurance.
- [ x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" …
=> JS objects video

content/javascript/concepts/functions/functions.md
Watch video through for quality assurance.
=> JS functions video

.markdownlint.yaml, content/python/concepts/inheritance/inheritance.md, package.json, yarn.lock
Adjust package versions to resolve version mismatch errors with local npm install.
=> Align versions to resolve npm install errors

content/powershell/powershell.md
=> Updated powershell.md description and content

content/go/concepts/variables/variables.md
An update to the Variable entry under Go concepts, to correct a typo and provide clarification to a number of sections. Edits include a typo (an extra comma) as well as expanding on a number of issues discussed in the entry:
- Notes specific to constants
- What characters are permissible in variable names
- The use of zero values by default in Go
- The requirement that variables are read
- [x ] I have made corresponding changes to the …
=> [Edit] Go Concepts: Variables

content/cybersecurity/concepts/penetration-testing/penetration-testing.md
Closes #2091 
I have added a penetration-testing folder to content > cybersecurity > concepts. In this folder, I've added a markdown file that explains what Penetration Testing is and who would conduct a pen test. I've also linked to other cybersecurity terms within Docs including ethical hackers, cyber attack, and red team.
- [ x] I have confirmed that …
=> Closes #2091 [Concept Entry] Cybersecurity Penetration Testing

content/ai/concepts/chatgpt/chatgpt.md
Fixed the year on the paper. (I know that is being picky, but it's a really big paper in ML/NLP :))
Source: https://papers.nips.cc/paper_files/paper/2017/file/3f5ee243547dee91fbd053c1c4a845aa-Paper.pdf
=> Fixed year on paper and a couple typos

content/php/concepts/math-functions/terms/is-nan/is-nan.md
Added a new term entry for **PHP** about `is_nan` function.
=> Added a term entry for is-nan in PHP (#2087)

content/general/concepts/software-development-life-cycle/terms/agile-model/agile-model.md, content/general/concepts/software-development-life-cycle/terms/spiral-model/spiral-model.md, content/general/concepts/software-development-life-cycle/terms/waterfall-model/waterfall-model.md
Include "Model" in title and rename folder/files to match.
Adjust description to start with verb.
=> Rename General SDLC terms

content/php/concepts/math-functions/terms/tan/tan.md
=> added the tan() function

content/php/concepts/string-functions/terms/str-shuffle/str-shuffle.md
This closes #2012 . Thanks for assigning me.
=> php-function-str_shuffle

content/java/concepts/methods/methods.md
Change "Pody" ➡️ "Body"; feedback form request
=> [Edit] Java Methods (Typo)

content/sql/concepts/math-functions/terms/power/power.md
This closes #2219 . Thanks for assigning me.
=> sql-math-function-power

content/sql/concepts/math-functions/math-functions.md
This Closes #2215 . Thanks for assigning me. Let me know what you think about it. 
Greetings, Niko.
=> sql-math-functions

content/c-sharp/concepts/arrays/terms/clear/clear.md, content/c-sharp/concepts/arrays/terms/length/length.md, content/c-sharp/concepts/arrays/terms/resize/resize.md
Hi, thanks for assigning. I added short codebytes. Let me know if they are good or if they should be longer.
This closes #2153 .
=> add-c#-codebytes

content/javascript/concepts/dates/terms/getDate/getDate.md, content/javascript/concepts/dates/terms/getDay/getDay.md, content/javascript/concepts/dates/terms/getHours/getHours.md
- The following terms were updated:
- JavaScript/Dates: .getDate(),
- JavaScript/Dates: .getDay(),
- JavaScript/Dates: .getHours(),
- The following changes were made:
- Add codebyte example,
- Fix typos,
- Update term definitions to match other terms
- Closes: #2226 
=> Edit javascript codebyte1

content/python/concepts/built-in-functions/terms/getattr/getattr.md
- Added the getattr() term for Python
- Closes issue #2142 
=> [Term Entry] python Built-in Function: getattr() 

content/sql/concepts/math-functions/terms/floor/floor.md
Thanks for assigning me. This closes #2218 . I used the example i removed from the math-functions concept entry. 
=> Sql-math-function-floor

content/sql/concepts/math-functions/terms/ceiling/ceiling.md
Hi, thanks for assigning me. This closes #2217 .
=> sql-function-ceiling

content/swift/concepts/arrays/terms/append/append.md, content/swift/concepts/arrays/terms/contains/contains.md
Bold any mentions of big O notation.
Closes #2222
=> [Edit] Swift Bold Big O

content/r/concepts/conditionals/conditionals.md
Added information on conditionals in R at docs/content/r/concepts/conditionals/conditionals.md.
- [✅] All writings are my own.
- [✅] My entry follows the Codecademy Docs style guide.
- [✅] My changes generate no new warnings.
- [✅] I have performed a self-review of my own writing and code.
- [✅] I have checked my entry and corrected any misspellings.
- [✅] I have made corresponding changes to the documentation if needed.
- [✅] I have confirmed my changes are not being pushed from my forked `main` branch.
- [✅] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [✅] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).
=> R conditionals

content/javascript/concepts/arrays/terms/slice/slice.md, content/javascript/concepts/arrays/terms/toString/toString.md
@yoiang  please review my changes 
issue #2277
Add code bytes for array slilce() and array toString() method 
This PR adds two new codebytes to the javaScript documentation that demonstrate how to use these two methods 
the first code byte shows  how to create a copy of a portion fo an array using the slice() method. 
the second code byte shows how to  convert an array into a string using the toString() method. 
these code bytes provide clear and concise examples that will help reader to understand how to use these important array methods.
=> added codebyte to JavaScript arrays to slice and toString method 

content/javascript/concepts/window/window.md
Concept entry for JavaScript `window` object.
=> [Concept Entry] JavaScript Window

bin/concept-of-the-week.txt, content/sql/concepts/math-functions/terms/abs/abs.md
This closes #2216 . Thanks for assigning me.
=> sql-math-function-abs

content/javascript/concepts/dates/terms/getFullYear/getFullYear.md
I have added a new file called `getFullYear.md` which describes the `getFullYear()` method in JavaScript.
=> Added entry to describe the getFullYear method in javascript

content/javascript/concepts/dates/terms/getFullYear/getFullYear.md
There was a missing period in the `.getFullYear()` metadata
=> Fix Typo in getFullYear

content/javascript/concepts/dates/terms/now/now.md, content/javascript/concepts/dates/terms/toLocaleDateString/toLocaleDateString.md
Thanks for assigning. This closes #2279 . 
=> add-js-codebytes

content/javascript/concepts/arrays/terms/length/length.md, content/javascript/concepts/arrays/terms/map/map.md
Adding Codebytes for the JavaScript array length property and map() method as requested on issue #2224. This PR closes issue #2224.
Files modified:
- content/javascript/concepts/arrays/terms/length/length.md
- content/javascript/concepts/arrays/terms/map/map.md
I am working on the Codecademy Front End Engineer path and the process of contributing to the Codecademy docs was introduced as part of the "Learn Git and GitHub" course (see project task here: https://www.codecademy.com/courses/learn-git/kanban_projects/contributing-to-the-codecademy-docs-repository). I have already made one contribution and, in the spirit of learning and community, decided to do another.
=> Closes Issue #2224 2.0

content/javascript/concepts/dates/terms/getUTCFullYear/getUTCFullYear.md
@caupolicandiaz and @SSwiniarski already revie this file. Changes applied.
getUTCFullYear folder  created in the specified path: docs/content/javascript/concepts/dates/terms/
Inside the folder you can find the getUTCFullYear.md file
=> Get utc full year issue

content/go/concepts/math-functions/math-functions.md, content/go/concepts/math-functions/terms/abs/abs.md
In the interest of filling out our Go entries, I created a Math Functions concept so we can start producing issues for Go math functions. I included one term so that the list wouldn't be empty when this is merged.
=> [Concept Entry] Go Math Functions.

content/javascript/concepts/dates/terms/getUTCDate/getUTCDate.md
Adding a new entry for the javascript getUTCDate to resolve issue #2337
=> added new entry for javascript getUTCDate method

content/go/concepts/strings/strings.md, content/go/concepts/strings/terms/count/count.md
I updated the Go Strings concept to introduce string functions, and added one string function term to start out the list.
=> Update Go Strings to list String Functions.

content/python/concepts/built-in-functions/terms/setattr/setattr.md
- Added the setattr() built-in function for Python
- Closes Issue #2386 
=> [Term Entry] Python Built-in Function: Setattr()

content/html/concepts/elements/terms/track/track.md
I added a new term to the HTML elements entry. It closes issue #2343.  
=> [Term Entry] Create track.md

content/html/concepts/elements/elements.md, content/html/concepts/elements/terms/track/track.md
I think because of a missing line break the table in this entry isn't rendering properly on Docs.
=> Update HTML Elements Track

content/javascript/concepts/dates/terms/getUTCMinutes/getUTCMinutes.md
- Added .getUTCMinutes() method for Javascript
- Closes #2425 
=> Utc minutes

content/javascript/concepts/dates/terms/setDate/setDate.md
Create a new term entry for the JavaScript setDate method resolves #2428 
=> Add new term entry for javascript set date method

content/sql/concepts/math-functions/terms/cos/cos.md
Thanks for assigning. This closes #2262 .
=> sql-function-cos

content/javascript/concepts/dates/terms/setMinutes/setMinutes.md
As part of the Codecademy Git/GitHub course, I'm required to contribute to an open source repo. This change adds the `Date.setMinutes()` method term entry.
=> Closes [Term Entry] JavaScript Dates .setMinutes() #2432 

content/javascript/concepts/dates/terms/getUTCMonth/getUTCMonth.md
- Added .getUTCMonth() method for Javascript
- Closes #2426
- 
=> [Term Entry] JavaScript Dates .getUTCMonth() #2426 

content/javascript/concepts/dates/terms/getUTCMilliseconds/getUTCMilliseconds.md
This is a new entry for the .getUTCMilliseconds() method on the JS Date object. Closes #2341.
=> Get utc milliseconds

content/go/concepts/math-functions/terms/sin/sin.md
Closes #2441
I have created a new term entry for the Sin() function in Go. The entry provides an explanation of the function, its syntax, and an example to demonstrate its usage. The entry goes in `docs/content/go/concepts/math-functions/terms/sin/sin.md`
=> [Term Entry]Add entry for the Sin() function in Go language

content/javascript/concepts/dates/terms/setTIme/setTIme.md, content/javascript/concepts/dates/terms/setTime/setTime.md
Added setTime at `docs/content/javascript/concepts/dates/terms/setTime/setTime.md`
Closes #2501
=> added setTime.md

content/sql/concepts/math-functions/terms/acos/acos.md
I have wrote a term entry for the ACOS function in SQL for the issue "[Term Entry] SQL Math Functions ACOS #2265".
The file path to my changes is docs/content/sql/concepts/math-functions/terms/acos/acos.md
I *heavily* relied on the doc page for the COS function: https://github.com/Codecademy/docs/blob/main/content/sql/concepts/math-functions/terms/cos/cos.md
=> Complete term entry for ACOS SQL function

content/javascript/concepts/map/terms/delete/delete.md, content/javascript/concepts/map/terms/get/get.md
Closes #2405 
Added Codebyte Examples to the following entries.
https://www.codecademy.com/resources/docs/javascript/map/delete
https://www.codecademy.com/resources/docs/javascript/map/get
=> [Edit] JavaScript Add Codebytes Issue: #2405

content/javascript/concepts/dates/terms/setSeconds/setSeconds.md
added setSeconds.md at `docs/content/javascript/concepts/dates/terms/setSeconds/setSeconds.md`
solves #2500
=> added setSeconds

content/php/concepts/string-functions/terms/strtolower/strtolower.md
Thanks for assigning me. This closes #2435 .
=> php-function-strtolower

content/python/concepts/built-in-functions/terms/dir/dir.md
- recreate dir() function
- create new branch
- closes issue #2470 
=> New branch for dir built-in function

content/markdown/concepts/emojis/emojis.md
- I revised the title in the Emoji entry. 
- Closes #2475
=> fix: revise title

content/go/concepts/math-functions/terms/min/min.md
Addressing issue #2559 
- Adding a new entry go math function min
=> [Term entry] Go-math-function-min

content/go/concepts/math-functions/terms/pow/pow.md
- Added the Math.Pow() term for go
- Closes Issue #2507 
=> [Term Entry] Go Math Functions Pow()

content/html/concepts/elements/terms/input/input.md
=> Edit HTML Elements: input

content/go/concepts/math-functions/terms/round/round.md
- Added math.Round() term for go
- Closes Issue #2560 
=> [Term Entry] Go Math Functions Round()

content/go/concepts/strings/terms/replace/replace.md, content/java/concepts/date/terms/after/after.md
- Add `Date.after()` term for Java
- closes issue #2685 
=> [Term Entry] Java Date Method: .after()

content/go/concepts/strings/terms/fields/fields.md
=> Go strings Fields() added #2563

.github/workflows/post-merge-messages.yml, .github/workflows/post-merge-survey.yml
Added new event to post merge messages workflow
Renamed workflow to generic name
=> Automate the boring stuff

content/php/concepts/math-functions/terms/pi/pi.md
This is an attempt to further enhance the existing resource on pi.md. Instructed to create a temporary location of some known constants. Motivation stems from the observation on some existing resources on the subject with some known constants of the pi() function as inclusion.
- [ /] All writings are my own.
- [ /] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ /] I have confirmed that I'm pushing from a new branch named after …
=> Introduced enhancements to pi.md using constants.

content/cybersecurity/concepts/hacking/hacking.md
=> [Typo] Cybersecurity: Hacking

content/php/concepts/math-functions/terms/acos/acos.md
The [acos()](https://www.codecademy.com/resources/docs/php/math-functions/acos) codebyte example prints the tag `<br>` following the resulting value which can confuse the user, and serves no purpose in the example. 
A few options considered -
1) Include HTML tags and echo another example, which will serve the purpose of the `<br>` tag. 
2) Remove the tag from the echo statement altogether. 
3) Change the text from `<br>` tag to " Radians".
Considered option 3 as it also gives the user context of the mathematical unit of the value resulting from the acos() method call.
=> fix: Update codebyte example for PHP acos() method

content/php/concepts/math-functions/terms/atan/atan.md
- Added the atan() term for PHP
- Closes issue #2205 
=> [Term Entry] PHP Math Function: atan

content/go/concepts/math-functions/terms/cbrt/cbrt.md
Closes #2755 
- Adding a term entry Go Math Function Cbrt
=> Go Math Function Cbrt

content/go/concepts/math-functions/terms/log/log.md
Created a new term entry for Go Math Function Log().
Closes #2757 
=> Added term entry for Go Math Function Log()

content/php/concepts/arrays/terms/extract/extract.md
I have added a new Term Entry for php extract function
Closes #2753 
=> [Term Entry] PHP Arrays extract() #2753

content/python/concepts/regex/terms/match/match.md, content/python/concepts/regex/terms/search/search.md, content/python/concepts/regex/terms/split/split.md
Closes #2889 
Added new codebyte examples for python - regex match, split and search
=> Python add codebytes

content/php/concepts/arrays/terms/shuffle/shuffle.md
Added The PHP Array function shuffle() which resolves #2822 
=> [Term Entry] PHP Arrays shuffle()

content/python/concepts/built-in-functions/terms/input/input.md, content/python/concepts/built-in-functions/terms/isinstance/isinstance.md
Added Codebytes To both Python Built-In Functions input() and isinstance()
Addressing issue #2817
- Editing an existing entry (fixing a typo, bug, issues, etc.)
=> [Edit] Python Built-In Functions Input() and isinstance() (Add Codebytes)

.github/scripts/urls.py, .github/workflows/post-merge-messages.yml
- Added scripts folder and file
- Added steps to workflow
Successful test case:
Actions: https://github.com/kt-codecademy/docs/actions/runs/5802256586/job/15728270207
PR Message: https://github.com/kt-codecademy/docs/pull/10#issuecomment-1670352551
=> Add script and append post merge workflow

.github/workflows/post-merge-messages.yml
Message works! Moving from Issues thread to PR thread
=> Move message from issues to pr

content/php/concepts/math-functions/terms/atanh/atanh.md
-Added the Math.atanh() term for PHP
-Closes issue #2398 
=> [Term Entry] PHP Math Functions: .atanh()

content/python/concepts/files/files.md, content/python/concepts/files/terms/read/read.md, content/python/concepts/files/terms/rmdir/rmdir.md, content/python/concepts/files/terms/seek/seek.md, content/python/concepts/files/terms/truncate/truncate.md, content/python/concepts/files/terms/unlink/unlink.md, content/python/concepts/files/terms/writable/writable.md, content/python/concepts/files/terms/write/write.md
Boldface markdown has been used for file names in multiple pages under content/python/concepts/files. Following discussion with @caupolicandiaz in [#2895](https://github.com/Codecademy/docs/pull/2895), these should be changed to backtick format.
This PR makes those edits to the relevant files. i.e. **filename.txt** has been changed to `filename.txt`.
=> Changed boldface to backticks for file names

content/java/concepts/calendar/terms/get/get.md
- Added `get()` method as a new term entry for the [Calendar](https://www.codecademy.com/resources/docs/java/calendar) class.
- New file has been created in `content/java/concepts/calendar/terms/get/get.md`
- Closes Issue #2973 
=> Added new [Term Entry] Java Calendar get()

content/java/concepts/calendar/terms/getDisplayNames/getDisplayNames.md
Added java term entry for getDisplayNames() method of the Calendar class. Closes #2980 .
- New Term for Existing Concept Entry
=> [New Term entry] added getDisplayNames.md

content/php/concepts/math-functions/terms/sqrt/sqrt.md
=> php new entry for sqrt function

content/php/concepts/arrays/terms/array-intersect/array-intersect.md
Added a new entry for the PHP function array(). The entry is in a new file in docs/content/php/concepts/arrays/terms/array-intersect/array-intersect.md.
Closes issue #2625 
=> [Term Entry]: PHP array-intersect()

content/markdown/concepts/mdx/mdx.md
This PR adds a new file called `mdx.md`, which explains the concept of MDX.
Closes #2872 
=> feat: adding entry about mdx

documentation/concept-entry-template.md, documentation/term-entry-template.md, documentation/topic-entry-template.md
I've updated the docs templates so that the description text ends with a period (per our std) and that the second content slug end in an "s" as required.
- [*] All writings are my own.
- [*] My entry follows the Codecademy Docs style guide.
- [*] My changes generate no new warnings.
- [*] I have performed a self-review of my own writing and code.
- [*] I have checked my entry and corrected any misspellings.
- [*] I have made corresponding changes to the documentation if needed.
- [*] I have confirmed my changes are not being pushed from my forked `main` branch.
- [*] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [*] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes …
=> [Edit] Template metadata 

content/markdown/concepts/mdx/mdx.md
This PR revises the code snippet about cookies and a few typos. By making these changes, developers and/or those who are learning about MDX would gain a better understanding of this entry. 
Closes #3011 
=> fix: revise code snippet format and typos

content/java/concepts/calendar/terms/compareTo/compareTo.md
Fixes #2969
Added compareTo() method of Calendar Class in Java
=> [TERM ENTRY]  Java Calendar CompareTo Fixes #2969

content/markdown/concepts/highlight/highlight.md, content/markdown/concepts/links/links.md
=> [Edit] Markdown: Links and Highlight

content/php/concepts/arrays/terms/array-reduce/array-reduce.md
Term entry for PHP's array_reduce function.
Closes #3045 
Updating documentation
=> [Term Entry] array_reduce() PHP

content/php/concepts/arrays/terms/array-unique/array-unique.md
- Added the term entry for array_uniqe() method in PHP.
- Closes #3050 .
=> [Term Entry] PHP Arrays array_uniqe()

content/php/concepts/arrays/terms/array-column/array-column.md
- Add the term entry for the array_splice method in PHP
- Closes issue #2876 
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).
=> [Term Entry] PHP Arrays array_column()

content/swift/concepts/structures/structures.md
Added a comment in ../swift/structures/structures.md file.
It is important that all structures properties conform to hashable protocol, so I added that part as a comment as a last part of the structure definition section. 
Also, added a link, so people can quickly look up Hashable values in documentation quickly.
=> New Entry: Added comment on hashable protocol conformation to ../swift/structures

content/uiux/concepts/wireframe/wireframe.md, documentation/tags.md
Adding `Design` as a tag to the `tags.md` file, and to test that adding tags suffices as an edit, adding the tag to the `wireframes.md` file.
=> add design tag and add to wireframes.md

content/go/concepts/strings/terms/tolower/tolower.md
Added term entry for Go String function `ToLower()` . File Location: `docs/content/go/concepts/string-functions/terms/tolower/tolower.md`
- [✓ ] All writings are my own.
- [✓ ] My entry follows the Codecademy Docs style guide.
- [ ✓] My changes generate no new warnings.
- [ ✓] I have performed a self-review of my own writing and code.
- [ ✓] I have checked my entry and corrected any misspellings.
- [ ✓] I have made corresponding changes to the documentation if needed.
- [ ✓] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ✓] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ✓] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue …
=> [Term Entry] Go Strings `ToLower()`

content/html/concepts/semantic-html/terms/ruby/ruby.md
Fixes a typo in the Semantic HTML `<ruby>` term.
=> Fix Typo in ruby.md

content/go/concepts/math-functions/terms/asin/asin.md
- Added new entry for Go/Math functions: Asin()
- Closes #3077 
=> Term entry go asin

content/go/concepts/math-functions/terms/asinh/asinh.md
- Added a new term for Go/Math functions: Asinh()
- Closes #3078 
=> Term entry go asinh

content/java/concepts/calendar/terms/getTime/getTime.md
Added entry for getTime() method of Java Calendar class. Closes #3096 .
=> [Term Entry] Java calendar getTime()

content/lua/concepts/strings/terms/upper/upper.md
- Added the string.upper() term for Lua
- Issue #3106 
=> [Term Entry] Lua Strings upper()

content/luau/luau.md
Add a Luau topic page so new concepts can be created and existing functions can be correctly identified under Luau.
=> [New Topic] Luau

content/java/concepts/calendar/terms/setMinimalDaysInFirstWeek/setMinimalDaysInFirstWeek.md
I have added a new term entry for the calendar class by creating a new file setMinimalDaysInFirstWeek used to set the minimal required days in first week of the year. This is my first time contributing to this repo so took time to make sure I did it well. 
- [] I have made corresponding changes to the documentation if needed.
=> [Term Entry] setMinimalDaysInFirstWeek()

documentation/content-standards.md, documentation/style-guide.md
Reflecting bolding in content standards
=> To bold or not to bold

content/java/concepts/calendar/terms/setLenient/setLenient.md
New Term Entry for ava Calendar setLenient(). Closes #3165 
=> Issue3165  Term Entry: setLenient() method

content/python/concepts/strings/terms/isascii/isascii.md
Closes #3276 
- Adding a new entry isascii.md under isascii file in python.
- Updating the documentation for python.
- [✔️] All writings are my own.
- [✔️] My entry follows the Codecademy Docs style guide.
- [✔️] My changes generate no new warnings.
- [✔️] I have performed a self-review of my own writing and code.
- [✔️] I have checked my entry and corrected any misspellings.
- [✔️] I have made corresponding changes to the documentation if needed.
- [✔️] I have confirmed my changes are not being pushed from my forked `main` branch.
- [✔️] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [✔️] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).
=> Added content for isascii for python

content/html/concepts/images/images.md, yarn.lock
There was an issue while displaying images on this page :
https://www.codecademy.com/resources/docs/html/images
Solved the issue by fixing a small error/typo in the code
=> Images display issue resolved

content/sql/concepts/commands/terms/cross-join/cross-join.md
- Closes issue #3395 
- Created cross-join.md on filepath docs/content/sql/concepts/commands/terms/cross-join/cross-join.md
- Added Title, Description, Subjects, Tags, and Catalog Content
- Added description, syntax, and example
- Ran through three online plagiarism checkers to ensure 100% unique wording and description, passed with 100% on all three
- Followed content and style guidelines 
- Checked for spelling and grammar errors
- Checked for clarity and readability
=> Create cross-join.md 

content/ai/concepts/search-algorithms/terms/stochastic-gradient-descent/stochastic-gradient-descent.md
- Created concept entry for Stochastic Gradient Descent AI search algorithm.
- Closes issue - #2135 
=> [Concept Entry]: AI Stochastic Gradient Descent

content/kotlin/concepts/math-methods/math-methods.md
Establishes the math methods base concept page to expand the kotlin entries to include available math methods
- [/ ] My entry follows the Codecademy Docs style guide.
- [/ ] My changes generate no new warnings.
- [/ ] I have performed a self-review of my own writing and code.
- [/ ] I have checked my entry and corrected any misspellings.
- [/ ] I have made corresponding changes to the documentation if needed.
- [/ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [/ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [/ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" …
=> [New Concept]Kotlin: Math-methods

content/swiftui/concepts/navigation/navigation.md, content/swiftui/concepts/viewmodifier/terms/background/background.md
Fix some typo in swiftui documentation
=> Typos swiftui topic

content/c-sharp/concepts/arrays/arrays.md, content/c-sharp/concepts/arrays/terms/copyto/copyto.md, content/c-sharp/concepts/strings/terms/equals/equals.md, content/c-sharp/concepts/strings/terms/lastindexof/lastindexof.md, content/c-sharp/concepts/switch/switch.md
Correct some typo in c-sharp documentation
=> Typos c sharp topic

content/javascript/concepts/this/this.md
This pull request corrects a typo (behavor -> behavior) in the file content/javascript/concepts/this/this.md.
=> Fix typos in ./content/javascript/concepts/this/this.md

content/cybersecurity/concepts/malware/terms/trojan/trojan.md, content/cybersecurity/concepts/nmap/terms/ping-sweep/ping-sweep.md, content/cybersecurity/concepts/risk/risk.md
Fix some typo in cybersecurity documentation
=> Typos cybersecurity topic

content/kotlin/concepts/math-methods/terms/max/max.md
=> add kotlin math max function to documentation

content/general/concepts/programming-paradigms/terms/object-oriented-programming/object-oriented-programming.md
Updating the page General > Programming Paradigms > Object Oriented Programming
Typo within the _Description_ field in the table at the top of the MarkDown file. This appears to be the text that populates within the LE docs tooltips
"scultping"  ->  "sculpting"
The same sentence is used within the doc body, but sculpting is already spelled correctly
raising as a result of this Curriculum Quality ticket: https://codecademy.atlassian.net/browse/CQ-6405
- [ x ] All writings are my own.
- [ x ] My entry follows the Codecademy Docs style guide.
- [ x ] My changes generate no new warnings.
- [ x ] I have performed a self-review of my own writing and code.
- [ x ] I have checked my entry and corrected any misspellings.
- [ x ] I have …
=> correct spelling

content/d3/concepts/scaling/terms/range/range.md, content/javascript/concepts/constructors/constructors.md, content/javascript/concepts/objects/objects.md, content/javascript/concepts/objects/terms/assign/assign.md, content/javascript/concepts/strings/strings.md
This PR makes the following edits to the String, Constructors, and Objects entries.
- Several of these had metadata sections that did not meet our standards
- Missing description and missing boldface formatting for the first instance of the subject
- Additional cross-linking
- Addition of some content to expand the scope of the entry
- [/ ] My entry follows the Codecademy Docs style guide.
- [/ ] My changes generate no new warnings.
- [/ ] I have performed a self-review of my own writing and code.
- [/ ] I have checked my entry and corrected any misspellings.
- [/ ] I have made corresponding changes to the documentation if needed.
- [/ ] I have confirmed my changes …
=> [Edit] JS: Concepts

content/javascript/concepts/objects/terms/getOwnPropertyDescriptors/getOwnPropertyDescriptors.md
Added getOwnPropertyDescription for Javascript Object terms. closes #4060 
=> add getOwnPropertyDescription Entry

content/react/concepts/hooks/terms/useRef/useRef.md
Fix typo in `content/react/concepts/hooks/terms/useRef/useRef.md`
=> Fix typo in useRef.md

CONTRIBUTING.md
I noticed some error in puctations I wanted to let you know
=> Fixing punctuations

content/java/concepts/errors/errors.md
Add common ways to handle multiple errors in a try-catch block in Java.
=> Add common ways to handle multiple errors in a try-catch block in Java

content/java/concepts/map/terms/containsKey/containsKey.md
- Created new term entry for Java `map.containsKey()`
- Closes #4180 
=> [Entry] Java Hashmap: Create the term entry map.containsKey()

content/javascript/concepts/dates/terms/getUTCDay/getUTCDay.md
- Added Codebyte Example for getUTCDay() method in Javascript.
- Closes issue #4141 
=> [Term entry] JS Date Method getUTCDay()

content/css/concepts/position/terms/top/top.md
Edited top.md image links to accurately reflect the names of the images in the media folder. Corrected the mistake from pull request #4077.
=> Fix image links

content/dart/concepts/switch/switch.md
- Added the Switch Statement concept entry for Dart
- Closes issue #4253 
=> [Term Entry] Dart Switch Cases: Switch Statements

content/general/concepts/software-testing/software-testing.md
=> Improved intro about software testing, providing more context.

content/python/concepts/collections-module/terms/defaultdict/defaultdict.md
- Added new term entry for the 'defaultdict' datatype in Python
- Closes #4232 
=> [Term Entry] Python: defaultdict

content/general/concepts/developer-tools/terms/code-editor/code-editor.md
Remove Atom from the list of code editors due to it being sunsetted.
=> [Edit] Developer Tools: Code Editor

content/discrete-math/concepts/congruences/congruences.md
Removing the extraneous `\` in the LaTeX code block under Transitive Property which is returning an error. 
=> [Typo] Discrete Math: Congruences 

content/java/concepts/array-list/terms/contains/contains.md
=> [Term Entry] Java ArrayList .contains()

content/git/concepts/pull-requests/pull-requests.md
- Added note under Method 1: Fork explaining exactly when a fork is needed.
- Closes Issue #4377 
=> [Edit] Git: Pull Requests - Add Note 

content/dart/concepts/map/terms/length/length.md
In this pull request, I added directories and a length.md file as shown below:
content/dart/concepts/map/terms/length/length.md
I followed the term-entry-template to add information about the length property in dart.
The issue is complete to my knowledge. If there is anything you would like changed, please let me know and I am happy to fix it!
Closes #4371 
- Updating the documentation (the only file that was edited was the file that was created: length.md)
=> added length.md documentation

content/dart/concepts/list/terms/getRange/getRange.md
I have created a new documentation entry for the .getRange() method under the Dart programming language section. This entry provides an overview of the .getRange() method, including its purpose, syntax, and a practical example demonstrating its use in retrieving a specific range of elements from a list.
Closes #4306 
=> added new entry-dart-getRangeMethod-issue#4306

content/general/concepts/database/database.md
Broken URL in https://www.codecademy.com/resources/docs/general/database for https://www.codecademy.com/resources/docs/general/database/relational-database
```md
Relational Databases
[Relational databases](https://www.codecademy.com/resources/docs/general/relational-database) structure their data in tables made up of rows and columns.
```
=> Update database.md with correct Relational Database url

README.md
Rewrote the "How do I Contribute?" section to include issue assignment step.
=> [Edit] README: Improve "How do I Contribute?" section

content/dart/concepts/strings/terms/length/length.md
- Added a new entry length.md file on the topic "Dart String .length()"
- Closes #4376
=> Created the structure and content for Dart Strings length method

content/numpy/concepts/built-in-functions/terms/variance/variance.md
- Added the NumPy built-in-functions numpy.var() term
- Closes #4476 
=> [Term Entry] Python: NumPy built-in-functions Variance 

content/numpy/concepts/built-in-functions/terms/median/median.md
- Added the numpy.median() term for NumPy
- Closes #4472 
=> [Term Entry] Python:NumPy built-in-functions .median()

documentation/catalog-content.md, documentation/tags.md
I've added the Catalog Content and Tags related to the new issues that were posted this week and last week as well.
=> Added the catalog subjects and tags for new issues

content/general/concepts/julia/julia.md, content/julia/julia.md
Adding Julia programming language to the docs.
=> add Julia programming language

content/html/concepts/attributes/terms/style/style.md
Noticed this image wasn't displaying correctly. Very small fix to the path/url. Please let me know if it needs a corresponding issue, but it seems like a quick change.
~~- Adding a new entry~~
~~Updating the documentation~~
=> Correct Broken Image Link

content/pillow/pillow.md
Added a topic entry for the Pillow Library in Python.
- [xx] My changes generate no new warnings.
=> [Topic Entry] Python: Pillow

content/java/concepts/array-list/terms/clone/clone.md
Added a new term entry for the `.clone()` method in Java.
Closes #4336
=> [Term Entry] Java ArrayList: .clone()

content/pytorch/pytorch.md
Topic Entry on PyTorch
- Creating new topic for PyTorch
=> [Topic Entry] PyTorch

content/javascript/concepts/arrays/terms/slice/slice.md
In the metadata, a clear definition for 'shallow copy' is added to make the term understandable for learners.
=> [Edit] JavaScript Arrays: .slice()

content/dart/concepts/map/terms/values/values.md
Added a new term entry for the `.values` property in Dart.
Closes #4368
=> [Term Entry] Dart Maps: .values

content/general/concepts/llm/llm.md
- Adding a new entry required in the catalog course.
=> [Topic Entry] Created `llm.md`

content/general/concepts/tokenization/tokenization.md, documentation/tags.md
=> [Concept Entry] Added a new entry `tokenization.md`

content/numpy/concepts/built-in-functions/terms/correlation-coefficient/correlation-coefficient.md
Added a new term entry for the `.corrcoef()` method in NumPy.
Closes #4475
=> [Term Entry] Python:NumPy Built-In Functions: Correlation Coefficient

content/pytorch/concepts/tensors/terms/ones/ones.md
- Added the .ones() function for Pytorch
- Closes #4936  
=> [Term Entry] PyTorch Tensors .ones()

content/dart/concepts/inheritance/inheritance.md
New entry for Inheritance with different kinds of inheritance 
Closes #4250 
=> [New Entry] Inheritance in dart

content/cloud-computing/concepts/containerization/containerization.md
Available intended link to Data Science page.
=> docs(containerization): intended path link

content/c-sharp/concepts/methods/methods.md
Corrected an error in C# / methods documentation. 
Closes #5143 
- [ x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.
=> Edit for issue #5143

content/sql/concepts/dates/terms/extract/extract.md
=> added file for extract sql

content/javascript/concepts/switch/switch.md
Shorten description in JavaScript switch to less than 160 characters
Closes #5379 
=> edit: Shorten description in JavaScript switch

content/python/concepts/comments/comments.md
This PR addresses the request to shorten the description for the "Comments" entry in the Python section, as detailed in issue #5387. The original description was too lengthy and has been condensed to fit within 160 characters while retaining the original meaning. Additionally, minor formatting adjustments were made for consistency with the Codecademy Docs style guide.
#5387 
=> feat(update): comments.md

content/numpy/concepts/ndarray/terms/reshape/reshape.md
This is a modification of the reshape entry in Numpy. I'm attempting to add a ##Codebyte Example to contextualize further the existing reference
Closes #5368 
- [/] All writings are my own.
- [/] My entry follows the Codecademy Docs style guide.
- [/] My changes generate no new warnings.
- [/] I have performed a self-review of my own writing and code.
- [/] I have checked my entry and corrected any misspellings.
- [/] I have made correspo/nding changes to the documentation if needed.
- [/] I have confirmed my changes are not being pushed from my forked `main` branch.
- [/] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [/] I have linked any issues that are relevant to this PR in the `Issues Solved` section.
=> Modification of the reshape entry in Numpy

content/c-sharp/concepts/strings/terms/contains/contains.md, yarn.lock
Edited the contains method of strings in C# to contain additional info on comparisionType along with an example.
Closes #5397 
=> [Edit] C# Strings - Contains comparisionType

content/javascript/concepts/this/this.md
Update to the this entry for JavaScript to shorten the description to less than 160 characters
Closes #5378 
=> Update javascript concept of this entry

content/pytorch/concepts/nn/terms/loss-functions/loss-functions.md, content/pytorch/concepts/tensor-operations/terms/gather/gather.md
A new entry on the .gather() term under PyTorch
#5563
- [✅ ] All writings are my own.
- [✅ ] My entry follows the Codecademy Docs style guide.
- [ ✅] My changes generate no new warnings.
- [✅ ] I have performed a self-review of my own writing and code.
- [✅ ] I have checked my entry and corrected any misspellings.
- [ ✅] I have made corresponding changes to the documentation if needed.
- [✅ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [✅ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ✅] I have linked any issues that are relevant to this PR in the `Issues Solved` section.
=> [Term Entry]Py torch tensor operations .gather()

content/cpp/concepts/variables/terms/constant-variables/constant-variables.md, content/pytorch/concepts/nn/terms/loss-functions/loss-functions.md
A new entry on the Constant Variables term under C++
#5471
- [ ✅] All writings are my own.
- [✅ ] My entry follows the Codecademy Docs style guide.
- [✅ ] My changes generate no new warnings.
- [ ✅] I have performed a self-review of my own writing and code.
- [ ✅] I have checked my entry and corrected any misspellings.
- [ ✅] I have made corresponding changes to the documentation if needed.
- [ ✅] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ✅] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [✅ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.
=> [Term Entry]C++ variables constant variables

content/kotlin/concepts/arrays/terms/indices/indices.md
Added a new term entry on the `.indices` property in Kotlin.
Closes #5311
=> [Term Entry] Kotlin Arrays: .indices

content/plotly/concepts/graph-objects/terms/mesh3d/mesh3d.md
Fix image markdown syntax in mesh3d concept entry in Plotly.
=> Fix image markdown in mesh3d concept entry

content/numpy/concepts/math-methods/terms/rint/rint.md
Added a new term entry for NumPy - `.rint()`
Closes #5238 
=> [Term Entry] NumPy - `.rint()`

content/numpy/concepts/math-methods/terms/nansum/nansum.md
Added a new term entry for NumPy math methods - `.nansum()`
Closes #5244 
=> [Term Entry] NumPy - `.nansum()`

content/numpy/concepts/math-methods/terms/diff/diff.md
Added a new term entry for NumPy `.diff()`
closes #5245 
=> [Term Entry] NumPy - `.diff()`

content/python/concepts/math-module/terms/math-asinh/math-asinh.md
Added a new term entry on the `math.asinh()` method in Python.
Closes #5079
=> [Term Entry] Python Math Module: math.asinh()

content/python/concepts/math-module/terms/math-frexp/math-frexp.md
Added a new term entry on the `math.frexp()` method in Python.
Closes #5085
=> [Term Entry] Python Math Module: math.frexp()

content/ai/concepts/search-algorithms/terms/greedy-best-first-search/greedy-best-first-search.md
Edit entry - AI Greedy-Best-First-Search: Added sections for advantages and disadvantages of the algorithm
Closes #5393 
=> Edit entry: AI Greedy-Best-First-Search

content/c-sharp/concepts/strings/terms/trim/trim.md
Added a new term entry on the `.Trim()` method in C#.
Closes #5573
=> [Term Entry] C# Strings: .Trim()

content/javascript/concepts/hashtables/hashtables.md
Added codebyte example for the hash tables concept
Closes #4865 
=> added codebyte example

content/cpp/concepts/variables/terms/global-variables/global-variables.md
Added a new term entry on `Global Variables` in C++.
Closes #5472
=> [Term Entry] C++ Variables: Global Variables

content/sklearn/concepts/multioutput-regression/multioutput-regression.md
Added Concept Entry for Sklearn multioutput-regression
Closes #5000 
=> [Concept Entry] Sklearn multioutput-regression

content/python/concepts/os-path-module/terms/join/join.md
Removed `/` from `learn-python-3/lessons/` in the `.join()` term entry in Python.
Closes #4351
=> [Edit] Python OS Path Module: .join()

content/pytorch/concepts/tensor-operations/terms/permute/permute.md
Added a new term entry on the `.permute()` function in NumPy.
Closes #5758
=> [Term Entry] PyTorch Tensor Operations: .permute()

content/pytorch/concepts/tensor-operations/terms/scatter/scatter.md
Added a new term entry on the `.scatter()` function in NumPy.
Closes #5760
=> [Term Entry] PyTorch Tensor Operations: .scatter()

content/pytorch/concepts/tensor-operations/terms/row-stack/row-stack.md
Added a new term entry on the `.row_stack()` function in NumPy.
Closes #5759
=> [Term Entry] PyTorch Tensor Operations: .row_stack()

content/numpy/concepts/array-broadcasting/array-broadcasting.md
Added a new concept entry on `Array Broadcasting` in NumPy.
Closes #5693
=> [Concept Entry] NumPy: Array Broadcasting

content/javascript/concepts/iterators/iterators.md
Made grammar edits to the iterator.md concept file under in the Javascript language. The motivation came from wanting to contribute bite-sized changes to a high-quality doc, and also contributing for the first time.
N/A
=> fix grammar in Javascript iterator.md

content/pytorch/concepts/tensor-operations/terms/diagonal-scatter/diagonal-scatter.md
Added a new term entry on the `.diagonal_scatter()` function in PyTorch.
Closes #5761 
=> [Term Entry] PyTorch Tensor Operations: .diagonal_scatter()

content/pytorch/concepts/tensor-operations/terms/select-scatter/select-scatter.md
Added a new term entry on the `.select_scatter()` function in PyTorch.
Closes #5806  
=> [Term Entry] PyTorch Tensor Operations: .select_scatter()

content/pytorch/concepts/tensor-operations/terms/slice-scatter/slice-scatter.md
Added a new term entry on the `.slice_scatter()` function in PyTorch.
Closes #5807 
=> [Term Entry] PyTorch Tensor Operations: .slice_scatter()

content/pytorch/concepts/tensor-operations/terms/scatter-reduce/scatter-reduce.md
Added a new term entry on the `.scatter_reduce()` function in PyTorch.
Closes #5839 
=> [Term Entry] PyTorch Tensor Operations: .scatter_reduce()

content/c/concepts/control-statements/control-statements.md
Added a new entry on the `control statements` concept under C
Closes #5957 
=> [Concept Entry] C: Control Statements

content/lua/concepts/iterators/iterators.md
I noticed that the Lua page for iterators contains an incorrect iterator for iterating from 3 down to 1. This reverses the start/stop number to work as described. I have tested both the original content and the new content to make sure it works.
=> fix(lua): fix incorrect code for reversed lua iterator

content/pytorch/concepts/tensor-operations/terms/moving-tensors-across-devices/moving-tensors-across-devices.md
=> [Term Entry] PyTorch Tensor Operations: Moving Tensors Across Devices(CPU/GPU)

content/c/concepts/union/union.md
=> [Concept Entry] C: Unions

content/pytorch/concepts/tensor-operations/terms/vsplit/vsplit.md
Added a new term entry on the `.vsplit()` function in PyTorch.
Closes #6012 
=> [Term Entry] PyTorch Tensor Operations: .vsplit()

content/pytorch/concepts/tensor-operations/terms/vstack/vstack.md
Added a new term entry on the `.vstack()` function in PyTorch.
Closes #6013
=> [Term Entry] PyTorch Tensor Operations: .vstack()

content/scipy/concepts/scipy-integrate/terms/quad/quad.md
Added a new term entry on the `.quad()` function in SciPy.
Closes #5850
=> [Term Entry] Python:SciPy scipy.integrate: quad()

docs/content/general/concepts/cpu/cpu.md
Added a new Concept Entry for General: CPU
Closes #6064 
=> [Concept Entry] General: CPU

content/general/concepts/terminal/terminal.md
Added a new [Concept Entry] General:Terminal
Closes #6058 
=> [Concept Entry] General:Terminal

content/general/concepts/ram/ram.md
Added a [Concept Entry] for General: RAM
Closes #6063 
=> [Concept Entry] General: RAM

content/sklearn/concepts/linear-regression-analysis/linear-regression-analysis.md
- Fix the broken output image link for the example
- Fix the mathematical formula latex syntax
Closes #5940
=> [Edit] Sklearn: linear regression analysis

content/c/concepts/operators/terms/ternary-operator/ternary-operator.md, documentation/tags.md
Added a new term entry for C Operators: Ternary Operator
Closes #5934 
=> [Term Entry] C Operators: Ternary Operator

content/c/concepts/operators/terms/sizeof/sizeof.md
Added a new term entry on `sizeof()` in C.
Closes #5935 
=> [Term Entry] C Operators: sizeof()

content/pytorch/concepts/tensor-operations/terms/tile/tile.md
Added a new term entry on `.tile()` in PyTorch.
Closes #5928 
=> [Term Entry] PyTorch Tensor Operations: .tile()

documentation/catalog-content.md
added a new catalog path for pytorch
=> added a new catalog path for pytorch

content/data-science/concepts/hypothesis-testing/hypothesis-testing.md
Add a new entry on the Hypothesis Testing concept under data science.
Closes #6156
=> [Concept Entry] Data Science: Hypothesis Testing

content/ai/concepts/machine-learning/terms/weakly-supervised-learning/weakly-supervised-learning.md
Topic: AI: Weakly-Supervised Learning
File added: `docs/content/ai/concepts/machine-learning/terms/weakly-supervised-learning/weakly-supervised-learning.md`
Closes #5972 
- ~Editing an existing entry (fixing a typo, bug, issues, etc)~
- ~Updating the documentation~
=> [Concept Entry] AI: Weakly-Supervised Learning

content/ai/concepts/machine-learning/terms/self-supervised-learning/self-supervised-learning.md
Topic: AI: Self-Supervised Learning
File added: `docs/content/ai/machine-learning/terms/self-supervised-learning/self-supervised-learning.md`
Closes #5971 
- ~Editing an existing entry (fixing a typo, bug, issues, etc)~
- ~Updating the documentation~
=> [Concept Entry] AI: Self-Supervised Learning

content/data-science/concepts/hypothesis-testing/terms/z-table/z-table.md
Added a new [Term Entry] Data Science Hypothesis Testing:Z-table
Closes #6157 
=> [Term Entry] Data Science Hypothesis Testing:Z-table

content/pytorch/concepts/tensor-operations/terms/as-tensor/as-tensor.md
This is an attempt to create .as_tensor() entry for PyTorch
Closes #6097 
- [ / ] All writings are my own.
- [ / ] My entry follows the Codecademy Docs style guide.
- [ / ] My changes generate no new warnings.
- [ / ] I have performed a self-review of my own writing and code.
- [ / ] I have checked my entry and corrected any misspellings.
- [ / ] I have made corresponding changes to the documentation if needed.
- [ / ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ / ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ / ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.
=> Creation of as-tensor.md

content/markdown/concepts/code-blocks/code-blocks.md
The previous example that showed code blocks for 4 indented spaces is misleading, as it uses the three-backtick code block syntax inside of the code block:
Only using the indented spaces leads to output that doesn't align with the docs:
The correct way to do this would be to remove the three backticks, and indent *all four* lines by four backspace (with the middle two having eight total):
I found this to be a bit excessive though, especially for a beginner's tutorial. So I simplified it to only include the two middle lines:
N/A, I just found this while looking stuff up out of boredom :/.
<del>- Adding a new entry</del>
<del>- Updating the documentation</del>
=> Fix Markdown code block example

content/cpp/concepts/inheritance/terms/hybrid-inheritance/hybrid-inheritance.md
Add documentation for Hybrid Inheritance in C++
Closes #6021
=> Add documentation for Hybrid Inheritance in C++

content/javascript/concepts/events/events.md
enhanced events.md
Closes #6169 
=> Updated events.md

content/javascript/concepts/dom-manipulation/dom-manipulation.md, content/javascript/concepts/dom/dom.md
Dom Concept Entry
Closes #6171 
=> Dom Concept Entry

content/pytorch/concepts/tensor-operations/terms/bernoulli/bernoulli.md
Added a new term entry on `.bernoulli()` in PyTorch.
Closes #6143 
=> [Term Entry] PyTorch Tensor Operations: .bernoulli()

content/pytorch/concepts/tensor-operations/terms/normal/normal.md
Added a new term entry on `.normal()` in PyTorch.
Closes #6144 
=> [Term Entry] PyTorch Tensor Operations: .normal()

content/javascript/concepts/window/terms/stop/stop.md
=> Corrected link for the image

content/pytorch/concepts/tensor-operations/terms/randperm/randperm.md
Added a new term entry on `.randperm()` in PyTorch.
Closes #6245
=> [Term Entry] PyTorch Tensor Operations: .randperm()

content/pytorch/concepts/tensor-operations/terms/acos/acos.md
Added a new term entry on `.acos()` in PyTorch.
Closes #6247
=> [Term Entry] PyTorch Tensor Operations: .acos()

content/numpy/concepts/random-module/random-module.md
Created a new entry on the `Random Module` concept in NumPy.
Closes #6426
=> [Concept Entry] NumPy: Random Module

content/numpy/concepts/built-in-functions/terms/cumsum/cumsum.md
- Added the .cumsum() built-in function for Numpy
Closes #6412 
- [ x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.
=> [Term Entry] Python - NumPy built-in functions: .cumsum()

content/numpy/concepts/linear-algebra/linear-algebra.md
[Concept Entry] Python-NumPy: Linear Algebra
closes #6425 
=> [Concept Entry] Python-NumPy: Linear Algebra

content/python/concepts/strings/terms/endswith/endswith.md
Edited the existing term entry on `.endswith()` in Python.
Closes #6496 
=> [Edit] Python Strings: .endswith()

content/python/concepts/math-module/terms/math-floor/math-floor.md
Closes #6584 
- [ /] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ /] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [/ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.
=> [Edit] Python  math.floor()

content/python/concepts/strings/terms/strip/strip.md
Closes #6585 
- [ /] I have confirmed my changes are not being pushed from my forked `main` branch.
- [/ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ /] I have linked any issues that are relevant to this PR in the `Issues Solved` section.
=> [Edit] Python strip

content/python/concepts/built-in-functions/terms/zip/zip.md
Closes #6587 
- [/ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ /] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ /] I have linked any issues that are relevant to this PR in the `Issues Solved` section.
=> [Edit] Python .zip()

content/python/concepts/lists/terms/count/count.md
Closes #6627 
- [ /] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ /] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [/ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.
=> [Edit] Python .count()

content/java/concepts/array-list/array-list.md
Closes #6630 
- [ /] All writings are my own.
- [/ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ /] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ /] I have linked any issues that are relevant to this PR in the `Issues Solved` section.
=> [Edit] Java Arraylist

content/cpp/concepts/overloading/terms/seperate-overload/seperate-overload.md, documentation/tags.md
- [] I have checked my entry and corrected any misspellings.
=> [Term Entry]: Separate Overload

content/javascript/concepts/ajax/ajax.md
Edited the existing concept entry on `AJAX` in JavaScript.
Closes #7064 
=> [Edit] JavaScript: AJAX

content/cpp/concepts/arrays/terms/at/at.md
[Term Entry] C++ Arrays:at()
Closes #6786 
=> [Term Entry] C++ Arrays:at()

content/cpp/concepts/pointers/terms/swap/swap.md
[Term Entry] C++ - Pointers: .swap()
Closes #6869 
=> [Term Entry] C++ - Pointers: .swap()

content/python/concepts/keywords/terms/def/def.md
Created a new term entry on `def` in Python.
Closes #6964 
=> [Term Entry] Python Keywords: def

content/python/concepts/strings/terms/join/join.md
Edited the existing term entry on `.join()` in Python.
=> [Edit] Python Strings: .join()

content/numpy/concepts/random-module/terms/binomial/binomial.md
=> [Term Entry] NumPy Random Module: .binomial()

content/pytorch/concepts/tensor-operations/terms/erfinv/erfinv.md
=> [Term Entry] PyTorch Tensor Operations: .erfinv()

content/sql/concepts/math-functions/terms/radians/radians.md
Added a new term entry for the SQL RADIANS() math function. This entry includes:
- Clear documentation explaining how RADIANS() converts degree values to radians for use in SQL queries
- Proper syntax section with parameter details
- Two practical examples: converting a single value and converting a column of degree values in a table
- Result tables for each example to illustrate the output
Closes #7531
- ~~Editing an existing entry (fixing a typo, bug, issues, etc)~~
- ~~Updating the documentation~~
=> docs(sql): added syntax and example for RADIANS() function

content/pytorch/concepts/tensors/terms/randn/randn.md
Edited the existing term entry on `.randn()` in PyTorch.
=> [Edit] PyTorch: .randn()

content/ai/concepts/search-algorithms/terms/gradient-descent/gradient-descent.md
Edited the existing term entry on `Gradient Descent` in AI.
=> [Edit] AI: Gradient Descent

content/ai/concepts/search-algorithms/terms/simulated-annealing/simulated-annealing.md
Edited the existing term entry on `Simulated Annealing` in AI.
=> [Edit] AI: Simulated Annealing

content/ai/concepts/search-algorithms/search-algorithms.md
Edited the existing concept entry on `Search Algorithms` in AI.
=> [Edit] AI: Search Algorithms
